jshintrc

@wltsmrz Thanks for polishing up the jshintrc file. There are just two edits that I'd like to add: removing the `boss` and `W004` relaxing options. I also moved `laxbreak` to the end, that is one relaxing option that may have some readability benefits. And I removed `camelcase` since it has no effect.
I can't think of any cases where `boss` (assignments where comparisons are expected) or `W004` (redefining parameters) should be allowed, but if there is a rare case where someone really wants to use it, they can disable the jshint warning with the `// jshint ignore:line` comment directive. But I'd imagine that 99% of the time when these warnings fire it will be catching bugs for us.

[TASK] Update jshintrc

---

src/js/ripple/transactionmanager.js

result of a received transaction could be in 'tes' or 'tec'.

double check 'tes' code before emitting 'success'

---

src/js/ripple/pathfind.js

path create uses broadcast, so close must
use this too

[FIX] properly close path find request

---

src/js/ripple/request.js
test/request-test.js

This behavior is consistent with `ripple-lib` before https://github.com/ripple/ripple-lib/commit/8af5f9c2#diff-a8d289f91765fc0f634609ad7c15c239L227

[BUG] `Request.prototype.ledgerSelect` can accept ledger_index as String

---

src/js/ripple/amount.js
src/js/ripple/serializedtypes.js
test/amount-test.js
test/remote-test.js
test/serializedtypes-test.js

Behavioral changes:
remove allow_nan option (option to convert NaN to 0)
all overflow checking is done in canonicalize
to_text always returns a string ('NaN' instead of NaN)
from_quality disallows XRP/XRP quality

Cleanup amount.js

---

src/js/ripple/serializedtypes.js
src/js/ripple/transaction.js
test/serializedobject-test.js
test/transaction-test.js

treat memos as unknown binary, with optionally parsing unsynthesized hint fields
Re-calculating hashes for transactions from rippled was failing. This was due to ripple-lib assuming the binary hex in the MemoType and MemoFormat fields it was receiving for memos represented strings in utf8 format. This is true if the transaction and memo were constructed using ripple-lib, but not if it was constructed in a different way and contain another format.
This PR removes this assumption and moves the utf8 serializing to the transaction level and out of the serializer level.
@wltsmrz @sublimator @shekenahglory

[FIX] unsymmetric memo serializing

---

src/js/ripple/remote.js

I passed in {expand:false, transactions:false} and still got transactions with the ledger.

fix handling of false parameters in requestLedger

---

src/js/ripple/server.js
src/js/ripple/utils.js

- This would be helpful for us to analyze usage of ripple-lib for anyone
using the public rippled
See: https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L530

Set User-Agent Header with ripple-lib/{version}

---

src/js/ripple/orderbook.js
test/fixtures/orderbook.js
test/orderbook-test.js

We were calling `parseInt` on a string that looks like `12345342e-3`, which gave us `12345342` instead of `12345`.

[FIX] fix taker pays funded calculation

---

src/js/ripple/amount.js

Amount.ratio_human and Amount.product_human should only change and return the cloned Amount object.

[FIX] Amount: clone in ratio_human, product_human

---

src/js/ripple/orderbook.js

Since the function has a side effect, it's better to not return a value.
http://en.wikipedia.org/wiki/Command%E2%80%93query_separation

Remove return value of mergeDirectAndAutobridgedBooks

---

src/core/orderbook.js

For autobridged order books, emit 'model' event,
even if offers is empty, to indicate that
orderbook is loaded

[FIX] emit empty offers list (RT-3462)

---

docs/GUIDES.md

I added issuer information to the payment example. Without it, you get an unhelpful serializing error. 
Solution due to https://github.com/ripple/ripple-lib/issues/28

Added issuer to payment example in guide

---

src/api/ledger/orderbook.js
src/api/ledger/parse/orderbook-order.js
test/api-test.js
test/fixtures/book-offers-response.js
test/fixtures/get-orderbook-response.json

Orders in the order book are now "synthetic" in that the specification of the order does not necessarily match the specification used to initially specify the order (buy and sell can be flipped). This allows us to merge the X/Y order book with the Y/X order book, which is good because one of the two order books is redundant.

Merge flipped orderbook in getOrderbook

---

.flowconfig
bin/ci.sh
package.json
src/api/index.js
src/api/ledger/accountinfo.js
src/api/ledger/balances.js
src/api/ledger/orderbook.js
src/api/ledger/orders.js
src/api/ledger/parse/account-order.js
src/api/ledger/parse/account-trustline.js
src/api/ledger/parse/amount.js
src/api/ledger/parse/orderbook-order.js
src/api/ledger/pathfind.js
src/api/ledger/settings.js
src/api/ledger/transaction.js
src/api/ledger/transactions.js
src/api/server/server.js

1. Add flow to ledger/parse/account-order, trustline, orderbook-order
Use eslint plugin flowtype to allow flow type annotations. Babel-eslint emits errors when using the type keyword. This plugin works around the issue by stripping flow annotations before linting. Source: https://www.npmjs.com/package/eslint-plugin-flowtype
2. Add flow typecheck to api/ledger/pathfind
3. Add flow check to src/api: index, accountinfo, balances, orderbook-orders, settings, transaction, transactions
4. Add flow to api/server/server.js
5. Add flow-bin to dev dependencies and ignore it in flowconfig

Add flow to api

---

src/api/common/schemas/settings.json
src/api/transaction/settings.js
test/api-test.js
test/fixtures/api/responses/index.js
test/fixtures/api/responses/prepare-settings-field-clear.json
test/fixtures/api/responses/prepare-settings-flag-clear.json
test/fixtures/api/responses/prepare-settings-flag-set.json
test/fixtures/api/responses/prepare-settings-set-transfer-rate.json

'emailHash' and 'walletLocator' fields so they
can be cleared
cover api/transaction/settings.js with tests

fix settings.json schema to allow empty stings to

---

src/core/orderbook.js
test/fixtures/orderbook.js
test/orderbook-test.js
test/remote-test.js

OrderBook's `notify()` function is the entry point for orderbook notifications (created, modified, deleted offers). In this function,  `_subscribed` property is checked to be truthy, however, this property only means that the end user subscribed or unsubscribed. The orderbook can also disconnect automatically, if a connection to rippled is lost. When this happens, all of the orderbook's account funds caches are cleared, but `notify()` would still execute as normal, because the end user hasn't unsubscribed. So, with cleared caches, the default return value for cached account funds is `0`. But if `notify()` detects a deleted offer... you get it. The error is `Offer total cannot be negative` https://github.com/ripple/ripple-lib/issues/352
This pull request simply adds a check for `_synced` …

Fix orderbook notification while disconnected

---

src/core/transactionmanager.js
test/transaction-manager-test.js

Bug was introduced during linting that would cause the transaction Sequence to be ahead, causing terPRE_SEQ and AccountSet no-op filler transactions for every transaction submitted

Fix transaction sequencing

---

src/api/common/schemas/adjustment.json
src/api/common/schemas/pathfind.json
src/api/ledger/parse/payment.js
src/api/ledger/pathfind.js
test/fixtures/api/responses/get-paths-send-usd.json
test/fixtures/api/responses/get-transaction-payment.json
test/fixtures/api/responses/get-transactions.json

I'm not entirely sure this is the correct way to do it, but I'm pretty sure the previous behavior was wrong.

Fix counterparty logic in pathfind parsing

---

src/core/transaction.js
test/transaction-test.js

"The Paths field must not be an empty array, nor an array whose members are all
empty arrays."
https://ripple.com/build/transactions/#paths

Don't set empty paths

---

src/api/ledger/accountinfo.js
src/api/ledger/settings.js

I think the other "get" methods already are getting the last validated ledger.

Get validated ledger in getSettings and getAccountInfo

---

src/core/uint.js

parse_bn was removed in the move to elliptic so removing from_bn to match
If no one noticed before, and rues the day it was excised, we could always add it back in.

Remove UInt#from_bn

---

src/api/common/index.js
src/api/common/schema-validator.js
src/api/index.js
test/api-test.js

isValidAddress will be provided by ripple-address-codec and computeLedgerHash will be provided by ripple-lib-serialization

Remove computeLedgerHash and isValidAddress from API

---

src/core/amount.js
test/amount-test.js

First, let it be known I AM NOT SURE THIS WORKS. I am raising this PR in part to ask a question.
I do not see why we the code uses `-1000000000000000e-96` as consts.min_value, only to go and .abs() it a few lines later. Is it not valid to instantiate `IOUValue('1000000000000000e-96')`?

remove redundant abs from MIN_IOU_VALUE

---

src/api/ledger/pathfind.js

Example stack:
```
TypeError: Cannot read property 'join' of undefined
at formatResponse
(ripple-lib/dist/npm/api/ledger/pathfind.js:75:187)
```

Fix: Check for destination_currencies property

---

src/core/binformat.js
src/core/hashprefixes.js
src/core/index.js
src/core/remote.js
src/core/transaction.js
src/core/transactionmanager.js
test/remote-test.js
test/transaction-test.js

Re: https://github.com/ripple/rippled/commit/9e69bd5c56ae8b4ceb44b353fc75d8d9f6b21834
+ Update binformat
+ Add `SignerListSet` transaction constructors
+ Add transaction methods
**New transaction methods**
`multiSigningData(signing account) -> serializedobject` Internal method, called in multiSign() from reconstituted transaction to prepare signing data
`getMultiSigningJson() -> tx_json` Returns a normalized tx_json with empty SigningPubKey and canonical signature flag auto-filled
`multiSign(account, secret) -> signer` Multi-signs a transaction reconstituted from getMultiSigningJson()
`addMultiSigner(signer)` Add and sort new multi-signer in the format returned by multiSign(): {Account, SigningPubKey, TxnSignature}
`hasMultiSigners() -> boolean` Self-explanatory
`getMultiSigners() -> …

Add multisign helpers

---

src/core/transaction.js
src/core/transactionmanager.js
test/transaction-manager-test.js
test/transaction-test.js

+ `Signers` has been moved to tx_json for submit/submit_multisigned
+ Automatically set LastLedgerSequence, honor existing values
+ By default, LastLedgerSequence offset is unrealistically low. Users should call either `tx.setLastLedgerSequence()` or `tx.setLastLedgerSequenceOffset()` before `tx.getMultiSigningJson()` / multisigning

Autofill LastLedgerSequence for multisigned transactions

---

src/autobridgecalculator.js
src/orderbook.js
test/orderbook-autobridge-test.js
test/orderbook-test.js
test/remote-test.js

OrderBook: emit 'model' event only after last transaction in closed ledger
run AutobridgeCalculator only once in a ledger

more OrderBook performance optimizations

---

src/api/ledger/parse/ledger.js
test/api-test.js
test/fixtures/api/responses/get-ledger-with-settings-tx.json
test/fixtures/api/responses/index.js
test/fixtures/api/rippled/index.js
test/fixtures/api/rippled/ledger-with-settings-tx.json
test/mock-rippled.js

from rippled's `ledger` command, `metaData` must be renamed to `meta` to conform with the response from the `tx` command

rename metaData to meta

---

src/ledger/pathfind-types.js
src/ledger/pathfind.js
test/integration/integration-test.js

When specifying a fixed sending amount during a pathfind request, the source
amount is specified as a `send_max` field. This fixes a bug where the amount was
specified as `source_amount`. Leading to strange pathfinding behavior.
Example bad behavior (rippled pathfind request/response):
```json
{
"command": "ripple_path_find",
"source_account": "rM21sWyMAJY1oqzgnweDatURxGMurBs7Kf",
"destination_account": "raDjTrcEtyMqZT6s3PyKGcikUJqYNXUPPv",
"destination_amount": {
"currency": "EUR",
"issuer": "raDjTrcEtyMqZT6s3PyKGcikUJqYNXUPPv",
"value": -1
},
"source_amount": {
"currency": "USD",
"issuer": "rM21sWyMAJY1oqzgnweDatURxGMurBs7Kf",
"value": "9.9"
},
"id": 2
}
{
"id": 2,
"result": {
"alternatives": [
{
"destination_amount": {
"currency": "EUR",
"issuer": "raDjTrcEtyMqZT6s3PyKGcikUJqYNXUPPv", …
```

Fix: Specify send_max when pathfinding with a source amount

---

docs/index.md
docs/src/getFee.md.ejs

> api.connect().then(() => api.getFee().then(fee => console.log(typeof fee)));
> string

getFee returns a string not float

---

src/ledger/pathfind.js
test/api-test.js
test/fixtures/addresses.js
test/fixtures/requests/getpaths/no-paths-source-amount.json
test/fixtures/requests/index.js
test/fixtures/rippled/index.js
test/fixtures/rippled/path-find-srcAmtLow.json
test/mock-rippled.js

When pathfinding with source amount, we need to filter out paths where source
amount is not equal to the specified source amount. This is due to the behavior
of rippled when specifying a source amount during pathfinding.
Example:
```javascript
{
"command": "ripple_path_find",
"source_account": "rhFQQ4ATC6MDF9ghTq3qAoCsGbGtjnhcXF",
"destination_account": "rp91GUd5R3Rk3ipqW7XBdtrUJcX8epzGyb",
"destination_amount": {
"currency": "EUR",
"issuer": "rp91GUd5R3Rk3ipqW7XBdtrUJcX8epzGyb",
"value": -1
},
"send_max": {
"currency": "USD",
"issuer": "rhFQQ4ATC6MDF9ghTq3qAoCsGbGtjnhcXF",
"value": "1234567891"
},
"id": 2
}
{
"id": 2,
"result": {
"alternatives": [
{
"destination_amount": {
"currency": "EUR",
"issuer": "rp91GUd5R3Rk3ipqW7XBdtrUJcX8epzGyb",
"value": "3999889.62127857"
},
"paths_canonical": …
```

Filter insufficient source funds paths from pathfind results

---

docs/index.md
src/common/schemas/objects/amount.json
src/common/schemas/output/outcome.json
src/ledger/parse/amount.js
src/ledger/parse/payment.js
src/ledger/parse/utils.js
test/fixtures/responses/get-ledger-full.json
test/fixtures/responses/get-transaction-payment.json
test/fixtures/responses/get-transactions.json

"It is impossible to reliably compute the delivered amount from the metadata due
to fixed precision. If the partial payment flag is not set and the transaction
succeeded, the delivered amount should always be considered to be the amount
specified in the transaction."

Add deliveredAmount to payment outcome

---

package.json
src/common/connection.js
test/connection-test.js

if connection to server can't be established, reject Promise of `connect()` method caller,
instead of throwing error event on base object.

[FIX] fix connection error handling

---

src/ledger/pathfind.js
test/fixtures/requests/getpaths/send-all.json

Bug:
```js
api.connect().then(() => {
const pathfind = {
source: {
address: USDCold,
amount: {
currency: 'USD',
value: '1.00' // <<<< Rippled response has "1" not "1.00"
}
},
destination: {
address: EURCold,
amount: {currency: 'EUR'}
}
};
return api.getPaths(pathfind).then(paths => {
console.log('PATHS: \n', JSON.stringify(paths, null, 2));
});
}).catch(console.log);
```

FIX: Filtering source_amount pathfind correctly

---

docs/index.md
src/common/schemas/objects/settings.json

The description field for the transferRate settings field incorrectly states that the value is in "billionths" (as it is represented in rippled). RippleAPI actually takes it as a decimal (same as Ripple-REST).

[DOC] fix transferRate description

---

docs/index.md
docs/src/boilerplate.md.ejs
docs/src/offline.md.ejs

Without the destructuring assignment, the boilerplate code runs on many Node versions (I think down to 4.x, but I don't know for sure). That said, it should definitely run on 6.9.x LTS which was Geert's suggestion for a reasonable minimum version to support, so I updated the docs to specify that version.
With that, you don't need Babel-Node to run code that uses RippleAPI.

Docs: Require Node 6.9.0, update boilerplate to avoid destructuring assign

---

.gitignore
package.json
scripts/ci.sh
src/ledger/parse/escrow-creation.js
src/ledger/parse/fields.js
src/ledger/parse/payment-channel.js
src/ledger/payment-channel.js
src/offline/sign-payment-channel-claim.js
src/offline/verify-payment-channel-claim.js
src/transaction/escrow-creation.js

I was seeing some errors when I ran `lint`, this PR fixes them.
I love the automatic fetch of team linting config, I've never seen that before. But by writing it to `eslintrc` instead of the expected `.eslintrc`, automatic tooling (like Sublime and VSCode editor plugins) can't pick up the config. Your [style guide](https://github.com/ripple/javascript-style-guide) mentions the correct file location, so I'm assuming this was just a mistake and fixed it in this PR as well.

fix lint errors and configure eslintrc to automatically work /w tooling

---

package.json
src/api.js
yarn.lock

From the [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) docs:
>Babel includes a polyfill that includes a custom regenerator runtime and core-js.
>
>This will emulate a full ES2015+ environment and is intended to be used in an application rather than a library/tool. This polyfill is automatically loaded when using babel-node.
ripple-lib is already using babel to transpile all advanced features and add necessary polyfills, so loading "babel-polyfill" additionally is unnecessary.  Worse, it means that all polyfills are being double-loaded and potentially double-executed.
Removing this line results in a much smaller build (`ripple-latest.js` 1.4MB vs 1.7MB) and a much faster load time (`require("./ripple-latest.js")` 267ms vs 337ms).
*Also removed "babel-runtime" dependency (no …

remove unneccessary double-polyfills from runtime

---

src/common/connection.js
src/common/constants.js
src/common/serverinfo.js
src/ledger/balance-sheet.js
src/ledger/orderbook.js
src/ledger/orders.js
src/ledger/parse/account-order.js
src/ledger/parse/fields.js
src/ledger/parse/flags.js
src/ledger/parse/orderbook-order.js
src/ledger/parse/pathfind.js
src/ledger/parse/transaction.js
src/ledger/pathfind.js
src/ledger/transaction.js
src/ledger/transactions.js
src/transaction/escrow-creation.js
src/transaction/escrow-execution.js
src/transaction/order.js
src/transaction/ordercancellation.js
src/transaction/payment.js
src/transaction/settings.js
src/transaction/trustline.js
src/transaction/utils.js

Ran `yarn lint` and found some errors, fixed them automatically with `eslint --fix`

Fix small lint errors

---

docs/index.md
test/fixtures/requests/prepare-escrow-creation.json

The existing example of an escrowCreation transaction in the docs includes `allowCancelAfter` but not an `allowExecuteAfter` field (and also no condition field)—this is the exact arrangement that can cause "false escrows" like the ones Ripple mistakenly made with the first set of the 55B escrows—they can be finished by anyone at any time before the cancellation.
This PR edits the example test fixture to add an `allowExecuteAfter` field. This provides a better example, but _should_ be functionally identical as a test fixture because the stated `allowCancelAfter` date is still in the past.

[Docs] Improve escrow creation example to have ExecuteAfter date

---

README.md

```
> yarn install ripple-lib
yarn install v1.3.2
error `install` has been replaced with `add` to add new dependencies. Run "yarn add ripple-lib" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Change yarn install to yarn add

---

Gulpfile.js

In the process of working on https://github.com/ripple/ripple-lib/pull/840, I found that our webpack config prevents the `build` script (i.e. `yarn build`) from working when `node_modules` exists anywhere in the path.
For example, if ripple-lib is cloned to:
```
/Users/elliotlee/github/ripple-lib-browser-client/node_modules/ripple-lib
```
Then webpack will output a file containing this monstrosity:
```
/* 1 */
...
/***/ (function(module, exports) {
throw new Error("Module parse failed: Unexpected token (47:5)\nYou may need an appropriate loader to handle this file type.\n| import * as schemaValidator from './common/schema-validator'\n| \n| type APIOptions = {\n|   server?: string,\n|   feeCushion?: number,");
/***/ }),
...
```
The solution to this was found here: …

webpack config - include src instead of excluding node_modules

---

package.json

This should be an alternative to https://github.com/ripple/ripple-lib/pull/840
~~We need to run the `build` script for this file to exist, so how should we handle that?~~
~~Perhaps we can just make sure "./build/ripple-latest.js" is prebuilt and published to npm?~~
See also: https://github.com/ripple/ripple-lib/pull/844#issuecomment-363514078

Add "browser" property to package.json

---

package.json

/cc @intelliot 
Follow up from #847:
We should continue to publish `build/` directory so that our users can grab it from CDN's like [unpkg.com](https://unpkg.com/ripple-lib@0.18.1/build/ripple-latest.js). When publishing, we should make sure our `build/` directory matches the latest compiled `dist/` directory by also building right before publishing.

Add build to prepublish

---

tsconfig.json

They are very useful in developing stable applications with TypeScript.

Generate/publish *.ts.d

---

src/api.ts
src/common/connection.ts
src/common/types/commands/account_info.ts
src/common/types/commands/book_offers.ts
src/ledger/accountinfo.ts
src/ledger/balance-sheet.ts
src/ledger/balances.ts
src/ledger/ledger.ts
src/ledger/orderbook.ts
src/ledger/parse/payment-channel.ts
src/ledger/settings.ts
src/ledger/transaction-types.ts
src/ledger/transactions.ts
src/ledger/utils.ts
src/transaction/escrow-cancellation.ts
src/transaction/escrow-creation.ts
src/transaction/escrow-execution.ts
src/transaction/payment-channel-claim.ts
src/transaction/payment-channel-create.ts
src/transaction/payment-channel-fund.ts
src/transaction/payment.ts
src/transaction/settings.ts

I found that `tsc` was giving me these errors:
```
src/api.ts(99,15): error TS4031: Public property 'connection' of exported class has or is using private name 'RestrictedConnection'.
src/api.ts(109,24): error TS4063: Parameter 'options' of constructor from exported class has or is using private name 'APIOptions'.
src/api.ts(221,3): error TS4029: Public property 'connect' of exported class has or is using name 'connect' from external module "/Users/user/ripple/ripple-lib/src/server/server" but cannot be named.
src/api.ts(222,3): error TS4029: Public property 'disconnect' of exported class has or is using name 'disconnect' from external module "/Users/user/ripple/ripple-lib/src/server/server" but cannot be named.
src/api.ts(223,3): error TS4029: Public property 'isConnected' of exported …
```

Export types used by exported variables

---

package.json

The `types` property in `package.json` should point to main types declaration file.
via https://github.com/ripple/ripple-lib/pull/851#issuecomment-370236308

Point to types in package.json

---

src/common/types/objects/ledger.ts

This appears to originate from a mistake in the docs.
The actual name of the field is `accountState`.
- In rippled, [here is where `accountState` gets added to the response](https://github.com/ripple/rippled/blame/9af994ceb45a82861205bb9d0b8d845cec950524/src/ripple/app/ledger/impl/LedgerToJson.cpp#L167)
- [PR to update the docs](https://github.com/ripple/ripple-dev-portal/pull/324)

Ledger object - accountState supersedes accounts

---

src/transaction/payment.ts

Payment `source` and `destination` are defined as intersection types,  `Adjustment & MaxAdjustment` and  `Adjustment & MinAdjustment` respectively. But they should be union types instead. This problem was introduced during js to ts conversion.
Fixes https://github.com/ripple/ripple-lib/issues/866

Fix Payment source & destination types

---

.travis.yml

It's currently possible to merge code that fails linting without Travis noticing. We should enforce linting for code being reviewed/merged.

Add linting to travis

---

src/transaction/payment.ts

Builds on top of #870, ~should be okay to merge after that PR is merged in.~ #870 merged in, this is ready to review/merge. 
Uses some TS magic to make type checking easier, and also consolidates some destination/source amount logic to reduce repeated code.

 more clean up for min/max adjustments

---

docs/index.md
docs/src/transactions.md.ejs
src/common/schemas/specifications/payment-channel-claim.json
src/common/schemas/specifications/payment-channel-create.json
src/common/schemas/specifications/payment-channel-fund.json

- Adds the PayChan types to [the transaction types list](https://ripple.com/build/rippleapi/#transaction-types). (Pointed out by @michielbdejong )
- Adds more specificity to some of the PayChan field descriptions
- Corrects a reversal of the Balance and Amount fields in the PaymentChannelClaim documentation.

Improve Payment Channel documentation

---

docs/index.md
docs/src/sign.md.ejs
src/common/schema-validator.ts
src/common/schemas/input/sign.json
src/common/schemas/objects/private-key.json
src/transaction/sign.ts
src/transaction/types.ts
test/api-test.js
test/integration/http-integration-test.js

New method :
`signWithKeypair(txJSON: string, keypair: {privateKey: string, publicKey: string}, options: Object): {signedTransaction: string, id: string}`
Allow transaction signing for accounts that have not been created through a secret.

Adding the method signWithKeypair

---

package.json
yarn.lock

- Fixes #880 
- Uses `yarn upgrade` to update `yarn.lock`
I believe these are already the dependencies that would be used by ripple-lib consumers, so there's no additional risk/harm in updating `yarn.lock` here. There's still risk that dependencies could introduce breaking changes at any time; I think we should address this by reducing our number of dependencies and by pinning more dependencies to specific versions (don't use `^` or `~`).

Pin jsonschema to v1.2.2

---

package.json
yarn.lock

https-proxy-agent <= 2.1.1 (including 1.0.0) has a potential vulernability as documented in https://hackerone.com/reports/319532

Upgrade https-proxy-agent to version 2

---

docs/index.md
docs/src/getOrderbook.md.ejs
src/common/schemas/output/orderbook-orders.json
src/ledger/orderbook.ts
src/ledger/parse/orderbook-order.ts
test/fixtures/responses/get-orderbook-with-xrp.json
test/fixtures/responses/get-orderbook.json

Include the full `BookOffer` data under `data`
Fix #799

getOrderbook - return raw order data

---

docs/index.md
docs/src/boilerplate.md.ejs

`yarn install` is now deprecated in favour of `yarn add` which can handle dependencies.
This has already been fixed in `/README.md`.

Updated yarn command

---

src/ledger/pathfind.ts
test/api-test.js
test/mock-rippled.js

When pathfinding with a source amount, rippled can return paths where the source amount in the returned path is not equal to the requested source amount. These are known as "insufficient source funds paths."
ripple-lib removes these paths from the response, but the filter did not handle the case where the amount is specified in drops, rather than an IOU with a `value` field.
The pathfinding request asks to find paths that deliver as much as possible of the destination amount by spending up to X source amount. In the returned path, if the source amount is less than X, that means there is not enough liquidity to spend it all. This means a payment that was meant to convert the entire amount of the `send max` would fail. It may be useful to know how much of the `send max` would be spent, so …

Fix getPaths

---

src/common/errors.ts
src/index.ts
test/api-test.js

- The PendingLedgerVersionError message had an extra space in it
- FormattedTransactionType is useful for apps that want to work with the response from `getTransaction()`

Fix PendingLedgerVersionError message and export FormattedTransactionType

---

src/common/types/commands/account_objects.ts
src/common/types/commands/book_offers.ts

discovered in [PR#460](https://github.com/ripple/ripple-dev-portal/pull/460)
the rippled-api book_offers functions returns offers with a base type of `OfferLedgerEntry` not `OfferCreateTransaction`.
It appears that there is enough crossover between the two types that I haven't found anything that breaks after switching the type, but any code that is developed in the future would have expected offers to have fields such as `TransactionType: 'OfferCreate` when the offer really had the field 'LedgerEntryType: 'Offer'`.
This corrects the getOrderBook response by indicating that the `data` property of each order included in the bids/asks array of the response is now the correct type
This does not impact the getOrder, getTransaction, getTransactions, or getAccountObjects responses which either …

book_offers returns offers type OfferLedgerEntry

---

src/transaction/types.ts

I'm trying to simulate submitting orders on the network with my Typescript application to test my process, but the ts compiler errors when I try to put more than 1 change in the balanceChanges property of the Outcome type.
The Outcome property in FormattedTransactionType objects has a balanceChanges property which is structured as 
```[account: string]: [(format of a change object)]``` 
instead of 
```[account: string]: (format of a change object)[]```
This prevents me from putting multiple value changes in the array because it is looking for an array of size 1. My current workaround is to override the type in my app. 
If preferred, an alternative syntax would be:
```[account: string]: Array<(format of a change object)>```

Type balanceChanges should be array of changes not array with one change 

---

test/fixtures/rippled/book-offers.js

Currently, the `RippleAPI getOrderbook normal` unit test uses `requestBookOffersBidsResponse` when `taker_gets: 'BTC', taker_pays: 'USD'`. However, the values in the `request` are ignored, and defaults of `taker_gets: 'USD', taker_pays: 'BTC'` are used instead - notice that the base/counter currencies are swapped.
The same problem exists for `requestBookOffersAsksResponse`.
This PR fixes the test fixture by switching the return values for bids/asks.

Fix book-offers test fixture by swapping bids/asks

---

HISTORY.md
docs/index.md
docs/src/preparePayment.md.ejs
package.json
src/transaction/check-cancel.ts
src/transaction/check-cash.ts
src/transaction/check-create.ts
src/transaction/escrow-creation.ts
src/transaction/escrow-execution.ts
src/transaction/order.ts
src/transaction/ordercancellation.ts
src/transaction/payment-channel-claim.ts
src/transaction/payment-channel-create.ts
src/transaction/payment-channel-fund.ts
src/transaction/payment.ts
src/transaction/settings.ts
src/transaction/trustline.ts
test/api-test.js

Currently the `prepare*` methods synchronously throw on validation errors, even though they are asynchronous methods that return Promises. But if an error is thrown asynchronously, the method may reject the Promise instead.
It would be more sensible for them to consistently reject the Promise when there is an error.
I believe this is a breaking change, so we'll need to call it out in the release notes and documentation.

Change prepare* methods to reject Promise on error

---

src/common/connection.ts
src/common/types/objects/ledger.ts
src/common/utils.ts
src/ledger/parse/fields.ts
src/ledger/parse/ledger.ts
src/ledger/parse/utils.ts
src/offline/derive.ts
src/transaction/combine.ts
src/transaction/utils.ts

Fixes `(node:41150) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

Use Buffer.from and clean up a few things

---

docs/index.md
docs/src/prepareTransaction.md.ejs

The docs for `prepareTransaction()` include an errant address parameter. (The examples show the correct way to use the method.)

Fix prepareTransaction method specification

---

src/transaction/utils.ts

This resolves the following build error thrown by type definitions that extend `TransactionJSON` and have optional properties (X of type T) if compiling in strict mode:
```
transaction/types.d.ts:LL;L - error TS2411: Property 'X' of type 'T | undefined' is not assignable to string index type 'string | number | any[] | Amount'
```

fix: build fails with strict checks

---

src/transaction/types.ts

This PR is created according to issue https://github.com/ripple/ripple-lib/issues/995
**The gist**
Adding back the `deliveredAmount` field to the type `Outcome` based on the `getTransaction` api call from https://developers.ripple.com/rippleapi-reference.html#gettransaction,

Add deliveredAmount as optional field for type Outcome

---

HISTORY.md
docs/index.md
src/common/schemas/input/get-transaction.json
src/common/schemas/objects/instructions.json
src/common/schemas/output/prepare.json
src/transaction/utils.ts
test/api-test.js

Prevent prepareTransaction from overwriting values in txJSON

---

Gulpfile.js
package.json

This is a minimal set of fixes from #1005 that are required for browser builds to work.
tsconfig:
- Must set composite: false
- Must set declarationMap: false in order to use declaration: false
json-loader:
- Not needed with webpack >= v2.0.0 and in fact does not work
https-proxy-agent cannot be used in the browser

Fix browser builds

---

docs/index.md
src/common/schemas/input/get-paths.json
src/common/schemas/objects/destination-address-tag.json
src/common/schemas/objects/destination-exact-adjustment.json
src/common/schemas/objects/min-adjustment.json

`destination .address` is showing up twice because the descriptions differ. This makes them the same.
Fixes https://github.com/ripple/ripple-dev-portal/issues/574
Thanks @xrpinnovations

Docs: fix ripple/ripple-dev-portal#574

---

docs/index.md
src/common/schemas/input/get-balance-sheet.json
src/common/schemas/input/get-orders.json
src/common/schemas/input/get-paths.json
src/common/schemas/input/sign.json
src/common/schemas/objects/amountbase.json
src/common/schemas/objects/balance.json
src/common/schemas/objects/max-adjustment.json
src/common/schemas/objects/min-adjustment.json
src/common/schemas/objects/source-exact-adjustment.json

Just a find/replace on the schema text that goes into the README, to fix some style issues:
- Change 'Ripple address'→'XRP Ledger address'
- Change 'is exclusive with'→'cannot be used with'

Phrasing cleanup in schema descriptions

---

package.json
src/common/js/lodash.isequal.js
src/transaction/sign.ts
src/transaction/utils.ts
test/api-test.js
yarn.lock

When signing a transaction, we should decode the signedTransaction blob and check the integrity (accuracy) of the data.

Sign method - verify accurate encoding

---

docs/index.md
docs/src/boilerplate.md.ejs

Noticed the README still uses the old Node recommendations instead of the new one we agreed on for the [quickstart](https://github.com/ripple/xrpl-dev-portal/pull/518). Updated the README to match.

Docs: update recommended Node ver.

---

package.json
yarn.lock

Updated these two dependencies as Mocha had a vulnerability and TxParser needed to be updated for #1027 
This shouldn't have any upstream issues. The code changed in the TxParser was a BigNumber.js update. The changes in Mocha were security improvements and bug fixes. All tests passed on my local machine.

Update TxParser and Mocha

---

src/transaction/sign.ts
test/api-test.js

Per https://github.com/ripple/ripple-lib/pull/1026#issuecomment-534001389
When there are multiple representations of the same value
(for example, trailing zeros) the verification will fail.
This points users to the `error.data` object for details about
the failure, and adds a `diff` so that the cause of the
discrepancy can be seen at a glance.

Improve error message when signing fails

---

docs/index.md

Some description and an example added to explain why `signAs` option is compulsory for multi-signing scenarios.

Doc update for sign() method

---

src/index.ts
src/ledger/transaction.ts

The current error message, `ledger_index and LedgerSequence not found in tx`, is not helpful. The new message is `Transaction has not been validated yet; try again later` which should be accurate.

Improve getTransaction() error when tx has not been validated yet

---

.npmignore
package.json

We can cut the size of the npm tarball by about 78% by excluding the other files in `build/` (including only `ripple-latest-min.js`, which I think is the one that people should use most of the time).
- Remove .npmignore since it is overridden by package.json 'files'
- Include build/ripple-latest-min.js, not everything in build/
Before:
```
% npm publish --dry-run
[...]
npm notice === Tarball Details === 
npm notice name:          ripple-lib                              
npm notice version:       1.4.0-b2                                
npm notice package size:  1.9 MB                                  
npm notice unpacked size: 7.8 MB                                  
npm notice shasum:        5a28c5b629bdfa7299381d9d639673d0407f3233
npm notice integrity: …
```

Reduce dependency size

---

package.json
test/api-test.ts
test/broadcast-api-test.ts
test/connection-test.ts
test/hashes-test.ts
test/mocha.opts
test/rangeset-test.ts
test/shamap-test.ts
test/tsconfig.json
tsconfig-base.json
yarn.lock

This moves the test files from JS to TS. We fall back to a few "any" types here just to not block the main move from JS to TS, and then can come back to resolve those after if they're worth it (some uses of any actually make sense, for example testing bad input that TS would disallow but a JS user might do anyway).

Move tests to TypeScript

---

docs/index.md
docs/src/getAccountObjects.md.ejs

Add necessary blank line for the list to render properly. (xrpl.org's Markdown parser won't recognize the list without it.)

getAccountObjects doc fix

---

HISTORY.md
package.json

This updates the README and HISTORY files to document the new release. Once this PR is merged, I'll do the release on GitHub/npm, send [the release announcement email](https://groups.google.com/forum/#!forum/ripple-lib-announce), and open a PR to update the docs site.

Proposed 1.4.1

---

.travis.yml

Updated our testing matrix based on: https://nodejs.org/en/about/releases/
- Node 11 is no longer supported (not LTS)
- Node 12 added (active LTS)
- Node 13 added ("current" release)

Fix Node.js Testing Versions

---

.prettierrc

Does anyone mind if we add a .prettierrc file to the repo? If you have the either the VSCode plugin setup or the CLI tool installed, you can just run `> Format Document` and get automatic formatting. You can also configure it to auto-format on save. 
I use this in all of my projects at this point and love it. I'd recommend we set it up for the project (`yarn run format` to format the whole repo), but first just adding this config file only for the people who want it would be a good first step.

Add a prettier config

---

src/common/constants.ts

This PR relates to issue https://github.com/ripple/ripple-lib/issues/965 and the documented behaviour of the email hash value (https://xrpl.org/rippleapi-reference.html#settings) "use null to clear".
While the intended behaviour of preparing a settings transaction with `{"emailHash": null}` is to clear the email hash, the setTransactionFields method in `/src/transaction/settings.ts` sets the email hash to `'0'`. This is invalid according to the current validation rules, as a length check fails (32 characters). By defaulting to `'00000000000000000000000000000000'`, assuming that the validation rules are correct, we fix the bug and ensure the email hash can be cleared.

Update email hash default to allow proper clearing

---

src/common/connection.ts

Adds an immediate catch to the `_send` promise passed to `_whenReady` in case there is rejection before async handlers are added. If there is no rejection, the added async handlers would take precedence. In the case of immediate rejection, the error is returned to the  `_whenReady.catch` appropriately. In the case of successful resolution `_whenReady.then` is called.
The behavior can be reproduced in this way: 
```
const passThe = function(promise) {
return new Promise((resolve, reject) => {
setTimeout(() => {
promise.then(resolve, reject);
}, 500);
});
}
const promise = function(message) {
return new Promise((resolve, reject) => {
return reject(new Error(message));
});
}
passThe(promise('helloWorld')).then((res) => {
console.log(res, 'passThe fn res')
}).catch((e) => {
console.log(e, …
```

Fix Unhandled Promise Rejection Warning on message _send

---

docs/index.md
src/common/constants.ts
src/common/schemas/objects/settings-plus-memos.json
src/common/types/objects/settings.ts
test/fixtures/responses/get-settings.json
test/fixtures/rippled/account-info.json

This PR adds support for the tick size field introduced by the TickSize amendement (https://xrpl.org/known-amendments.html#ticksize)
The implementation follows the documentation in https://xrpl.org/accountset.html#accountset-fields, meaning that valid values are 3 to 15 inclusive and 0 is used to disable the custom tick size.

Add support for tick size

---

package.json

This library should be used with node 8 and yarn

[package.json] Require node 8 and yarn

---

docs/index.md
docs/src/getTransactions.md.ejs
test/fixtures/responses/get-transactions.json

I don't know why the prior example response didn't include `outcome.timestamp`; perhaps it was created using a much older version of ripple-lib, or the transactions were not yet validated at the time.

Update getTransactions example request/response

---

src/common/connection.ts
test/connection-test.ts
test/mock-rippled.ts

ripple-lib now keeps a constant heartbeat to detect broken/hung connections. Every minute, a "ping" command is sent by the RippleAPI connection instance. If that fails, the connection is disconnected so that the consumer can reconnect.
I was able to test this by dropping the timeout down to below the mocked "ping" response, to simulate a hung connection receiving no responses from the server. It's not perfect, but it's a fair enough representation, especially considering how tricky it is to test server disconnect/reconnect logic.
- Is "disconnect" the proper action? With a little more complexity, we could also reconnect automatically (silently so that the user never knows, or with emitted "disconnect" and "reconnect" events).  
- **A:** Talked with @intelliot, and we'll make "reconnect" …

Add a heartbeat to detect hung connections

---

src/api.ts
src/common/connection.ts
test/connection-test.ts

Changes trace from a `boolean` to a `boolean | function`, where the user can provide a function for logging the request/response (vs. having to monkey-patch the _console message in our tests).
The public API docs only mention the current boolean behavior, do we want to also mention that a function works as an option? It's fairly advanced usage, but could still be good to mention.

Cleanup the connection trace logic

---

src/api.ts
src/common/connection.ts
test/connection-test.ts

This moves all of the configuration state into a single `_config` property. The _config object is created from the user-provided config after the constructor cleans it (basically just sets some defaults).
This is nice because it gets all the user-provided configuration into a single property, which should scale nicely / not pollute the global `Connection` object with config values. However the is probably the most subjective of everything suggested in #1110, so if you prefer it as-is let me know.

Cleanup the connection config state

---

.eslintrc.json
package.json
src/common/hashes/shamap.ts

Our eslint invocation was using a glob (a file system matcher using `*` wildcards, regex, etc) that wasn't stringified, which meant that the unix system converts it into a list of files before passing it to eslint. Unix's globbing is less flexible than eslint, meaning we weren't linting as many deeply nested files as we meant to. 
The PR fixes our invocation by making sure that eslint gets the unmodified string, and then fixes a two issues that were found by running our linter on some files for the first time:
- no-dupe-class-members - This should be turned off for TypeScript, since method overloading is allowed in TS (for typing purposes) and actual duplicate class methods would be caught by the TypeScript compiler.
- [no-case-declarations](https://eslint.org/docs/rules/no-case-declaratio …

Fix incorrect eslint matching glob

---

src/common/connection.ts
test/connection-test.ts

This commit adds a unit test for ripple#1092 as requested. While writing the test it was realized that  ws module now throws an error on disconnected send whereas before it returned a callback. The error is now caught with ripple#1092 but I believe it should have the DisconnectedError type as well, so a try catch was added to set the error type properly in that case.

Adds unit test for ripple#1092, fixes unhandled throw on upgraded ws send

---

src/common/types/objects/ledger_entries.ts
src/common/types/objects/signers.ts

Does not match the structure returned by the API.
```:sample code
import {RippleAPI} from '.'
const main = async() => {
const api = new RippleAPI({server: 'wss://s1.ripple.com'})
await api.connect()
const object = await api.getAccountObjects('rDbWJ9C7uExThZYAwV8m6LsZ5YSX3sa6US')
for(const accountObject of object.account_objects){
if(accountObject.LedgerEntryType === 'SignerList'){
console.log(accountObject.SignerEntries[0].SignerEntry.Account)
}
}
}
main()
```

fix AccountObjectsResponse structure

---

docs/index.md
src/common/schemas/input/generate-address.json
src/common/schemas/input/generate-x-address.json

The documentation previously just stated that any array of integers was acceptable for providing as entropy, but it must be an array of length 16 where the values are from 0-255 (uint8) to ensure we have 16 bytes of entropy.

Improve documentation for address generation

---

src/common/connection.ts
test/connection-test.ts

Implements a change suggested in #1110.
- Moved ledger logic off of the Connection class and into it's own `Ledger` class.
- Updated `_whenReady(promise)` -> `_waitForReady()`. The old method appeared to not be working as expected: it was meant to run a promise after the connection was ready, but a promise would always start immediately at creation time.  Instead we just remove the promise argument, and resolve once the connection is ready. Then, the caller can wait for this to resolve before moving on to start the thing that needed to wait.
- There's a little bit of implicit behavior that I didn't get rid of: we assume that `waitForReady` will set some ledger data, so that methods like `getBaseFee()` will always return a number and never return null. It would be considered a bug if this …

Add LedgerHistory to Connection

---

src/common/connection.ts
test/connection-test.ts

This addresses a possible uncaught error on run of `this._heartbeat` and subsequently `this.reconnect()` as the reconnection promise could throw.
Emits an error event if `this.reconnect()` does throw as seen in other reconnect failures.

Catch possible error in reconnect() on _heartbeat(), emit reconnect error

---

src/common/connection.ts
test/connection-test.ts

This commit adds the Connection `_ws.close` event listener post `_ws.open` before executing any post `_ws.open` logic, i.e. `Connection._subscribeToLedger`.  This prevents a reconnection error loop that occurs if `Connection._ws` is never cleaned up by the unreachable `_ws.close` event listener. Also, this ensures that a possible disconnect() promise rejection is not unhandled if any `_ws.open` logic in `Connection.connect()` throws.

Assign event listener to socket close event on open before attempting post-open logic

---

package.json
src/offline/generate-address.ts
test/api/generateAddress/index.ts
test/api/generateXAddress/index.ts
test/ripple-api-test.ts
yarn.lock

Fix #1209
Calling:
- `Uint8Array.from(undefined)`
Throws:
- `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at Function.from (<anonymous>)`
Test coverage was poor, so I added a ton of new tests.

Fix generateXAddress() and generateXAddress() with no entropy

---

.travis.yml

ripple-address-codec 4.1.1 requires node 10+

Travis: remove node 8

---

src/api.ts
src/common/hashes/README.md
src/common/hashes/index.ts
src/common/hashes/ledgerspaces.ts
test/hashes-test.ts

The now-deprecated ripple-hashes library provided a number of hash
functions for users to compute the hashes/IDs for various XRP Ledger
objects:
* Transactions (to generate transaction hashes, also known as IDs)
* Transaction signing hashes (to sign transactions)
* Ledger Object IDs (to look up specific ledger objects in a ledger's
state tree; see https://xrpl.org/ledger-object-ids.html)
This commit exports these utility methods from ripple-lib as static
methods. Access them on the RippleAPI class. Example:
```
import {RippleAPI} from 'ripple-lib'
const hash = RippleAPI.computeBinaryTransactionHash(...)
```

Export hashing functions

---

.travis.yml
HISTORY.md
docs/index.md
docs/src/staticMethods.md.ejs
package.json
src/api.ts
src/common/connection.ts
src/common/constants.ts
src/common/hashes/README.md
src/common/hashes/index.ts
src/common/hashes/ledgerspaces.ts
src/common/schemas/input/submit.json
src/ledger/settings.ts
src/offline/generate-address.ts
src/transaction/submit.ts
test/api/generateAddress/index.ts
test/api/generateXAddress/index.ts
test/api/getTransaction/index.ts
test/connection-test.ts
test/hashes-test.ts
yarn.lock

* Export hashing functions (#1275)
* Add failHard (fail_hard) option in `submit` method (#1029)
* Add type for parseAccountFlags (#1258)
* Add api.connection.getReserveBase() (#1259)
* Travis: remove node 8 (#1257)
* Dependencies
* Update ripple-address-codec, @types/ws, @types/lodash, https-proxy-agent
* Update devDependencies: eventemitter2, nyc, ejs, @types/node, webpack, ts-node, prettier, @typescript-eslint/eslint-plugin

Release 1.7.0

---

docs/index.md
docs/src/generateXAddress.md.ejs

Fixes wrong `generateXAddress` example in API Methods.

Fix generateXAddress example

---

docs/index.md
docs/src/submit.md.ejs
src/api.ts
src/transaction/submit.ts

Using request('submit', ...) allows the ripple-lib API to be effectively
identical to the underlying rippled API. Whereas submit() returns only
certain fields from rippled, using request('submit') gives you rippled's
full response, including the new fields added in rippled v1.5.0.

Deprecate submit() in favor of request('submit', {...})

---

package.json
src/common/connection.ts

Published to npm as 1.8.2-beta.0. https://www.npmjs.com/package/ripple-lib?activeTab=versions
Install it as `ripple-lib@1.8.2-beta.0` or, since it is tagged as `beta`, use `ripple-lib@beta`

Proposed 1.8.2-beta.0

---

src/ledger/settings.ts

Aside from a numeric ledger index, we can also specify  'validated' | 'closed' | 'current'

getSettings: allow ledgerVersion to be validated, closed, or current

---

HISTORY.md
package.json
yarn.lock

Quick fix to prevent browser compatibility issues for now. We can bump to 1.x in ripple-lib 1.9 or 2.0.

Use ripple-binary-codec 0.2.x

---

package.json
snippets/src/reliableTransactionSubmission.ts

Here is one example approach
To run the example:
```
yarn run compile:snippets && node ./snippets/dist/reliableTransactionSubmission
```

Add example of reliable transaction submission

---

docs/index.md
src/common/schemas/output/get-ledger.json

I noticed that the `closeTime` and `closeTimeResolution` descriptions weren't quite right, so I updated them.

Improve descriptions of get-ledger response time fields.

---

docs/index.md
docs/src/specifications.md.ejs

While tracking down a broken link coming from the API reference, I found that not only was the "Ticket Create" specification missing, so were a couple of the other new transaction types. This PR rectifies that by doing the following:
- Add the following missing specifications to the list of transactionType specifications:
- Ticket Create
- Account Delete
- Deposit Preauth
- Rearrange the transaction type specifications to be in alphabetical order.
- Add descriptions to the transaction type specifications instead of linking back to the type table.
- Link transaction types to their corresponding native transaction type(s).

Add missing transaction specifications

---

docs/index.md
src/common/connection.ts
src/common/schemas/input/api-options.json

If the rippled server is down or inaccessible, the connect() method could hang for a long time. Previously, a connection timeout was added. The default was 2000 ms. This was too short; slower connections could take longer than that to connect.
This PR changes the default connection timeout to 5000 ms.
The `RippleAPI` constructor was meant to be able to take a `connectionTimeout` option, but the option was missing from the JSON schema (`api-options.json`), so it was not actually allowed to be used.
This PR adds the `connectionTimeout` option to the JSON schema.
Thanks to:
- @southbite 
- @madshell
- @koresar
- @nickewansmith 
- @kincaidoneil

Fix connectionTimeout option

---

docs/index.md
docs/src/specifications.md.ejs

https://github.com/ripple/ripple-lib/pull/1352 had empty placeholder links for a few transaction types. This adds those.

Docs: Add missing transaction type links

---

src/common/serverinfo.ts
test/api/getFee/index.ts
test/fixtures/rippled/index.js
test/fixtures/rippled/server-info-reporting.json
test/mock-rippled.ts

When using a rippled server in Reporting Mode, the server_info response does not have a load_factor property.
https://xrpl.org/rippled-server-modes.html#reporting-mode
https://github.com/ripple/rippled/issues/3812
Now, when load_factor is missing, we default to a load_factor of 1.
Fix #1398
Thanks to @LynchEntrostat @anhcao142

Prevent getFee from returning NaN from Reporting Mode

---

src/transaction/utils.ts

See #999 
This should make `tefPAST_SEQ` occur less often, and make the behavior consistent when connecting to a rippled server in Reporting Mode.

fix #999: use 'current' ledger when preparing txs

---

src/transaction/settings.ts

Currently, `prepareSettings` only accepts one setting: if you set `domain` and `emailHash`, then `prepareSettings` returns an error:
```
AssertionError [ERR_ASSERTION]: ERROR: can only set one setting per transaction
```
This PR fixes that.

fix: allow multiple settings at once

---

docs/index.md
docs/src/boilerplate.md.ejs

- Suggest XRPLF's public cluster; this is a better starter experience since it's full-history and blocks known scam accounts
- Update the Node.js compatibility language to match the README. (credit to nixerFFM for noticing the discrepancy)
- Remove dated language about ES5/ES6 Promises.
- Re-gen docs (this seems to have added a memo field that was previously modified in some other PR)

Update boilerplate docs

---

src/ledger/parse/account-trustline.ts
test/api/getTrustlines/index.ts
test/fixtures/responses/get-trustlines-rippling-disabled.json
test/fixtures/responses/index.js
test/fixtures/rippled/account-lines.js
test/mock-rippled.ts

This PR corrects a miscommunication with `ripplingDisabled`. Initially, it would have the value `undefined` if it was `false`, now it is `false`. The same issue is corrected with `frozen` and `authenticated`.
Fixes #1317 
Added a test that tests for this behavior, and made sure the other tests were still passing.

Fixes miscommunication with `ripplingDisabled` in trustlines

---

src/common/utils.ts
src/transaction/order.ts
src/transaction/payment.ts
src/transaction/utils.ts
test/api/prepareTransaction/index.ts
test/api/prepareTrustline/index.ts
test/fixtures/requests/index.js
test/fixtures/requests/prepare-trustline-issuer-xaddress.json
test/fixtures/responses/index.js
test/fixtures/responses/prepare-trustline-issuer-xaddress.json

Allow `Amount.issuer` to be represented as an X-Address with no destination tag.
fixes #1404
To allow for this behavior, we have to check each possible issuer in `prepareTransaction`, and ensure that all X-Addresses are converted to classic addresses.  
This behavior checks every possible Transaction field that could be an issued currency amount, and if its issuer is described with an X-address, then it converts it to a classic address. 
Added tests that verify that the scenarios in #1404 that were failing, no longer fail. This tests`prepareTransaction()` for a `Payment` transaction, and `prepareTrustline` for creating a trustline.

Allow XAddress Issuers

---

src/ledger/trustlines.ts
test/api/getTrustlines/index.ts
test/mock-rippled.ts

`getTrustlines` wasn't using `ledgerVersion` in the options at all, and was instead getting the current ledger version. This PR fixes that.
Fixes #1501 
Added a test to check for the correct behavior. CI passes.

Fixes ledger version in `getTrustlines`

---

src/api.ts

Removed an exit code we were supporting temporarily due to a ws library bug.
Responding to a TODO left 2 years ago to get rid of the conversion on the next breaking change. 
We were converting exit code 1005 to 1000 to be backwards compatible with old versions of the ws library which were incorrectly exiting with 1000 instead of 1005. (Link to issue: https://github.com/websockets/ws/issues/1257)
Before we were turning the exit code 1005 
CI tests pass

Removed legacy exit code conversion

---

test/localintegrationrunner.html
webpack.config.js

Stop excluding lodash from webpack build.
Previously, we would webpack ripple-latest without lodash, as it is a frequently used library. This really only saves ~80KB, which is not worth the hassle of not packaging these together.

build: include lodash in webpack build

---

src/models/methods/baseMethod.ts
src/models/methods/index.ts
src/models/methods/submit.ts
src/models/methods/submitMultisigned.ts
src/models/methods/transactionEntry.ts
src/models/methods/tx.ts

This PR creates new TypeScript types for all rippled transaction methods (https://xrpl.org/transaction-methods.html), and the request shapes and response shapes. `sign` and `sign_for` are purposely excluded, because the library has offline signing functionality, and it is unadvised to use those methods unless you are running your own rippled server.
xrpl.js v2.0 models
This PR doesn't change any existing code, so tests are fine.

Implements TypeScript types for transaction method requests/responses

---

docs/index.md
docs/src/sign.md.ejs
src/common/schemas/input/sign.json

* Added examples of what private and public keypairs look like for the sign method to give readers an intuition for the data type
* Added links to how keypairs are derived in rippled and ripple-lib so that they can dive deeper if they want to
Fixes #1045 
This is in response to #1045 to improve the documentation's covering of the two encodings ed25519 and secp256k1. 
There are also several changes being made in the xrpl-dev-portal to add examples of the keys to their derivation to help developers see what the keys actually look like.
Added links in the public key/private key fields for the sign api, and added an example of what keypairs look like in the two formats.
No tests for docs change.

Update sign docs with more info about keypairs

---

src/models/transactions/index.ts
src/models/transactions/offerCancel.ts
src/models/transactions/transaction.ts
test/models/checkCancel.ts
test/models/offerCancel.ts

There was an issue when AccountSet Tx Model was merged with 2.0 and OfferCancel was deleted. This PR fixes that.
This PR was tested using `yarn test` and everything seems to work fine!

fix: resolve OfferCancel merge issues

---

snippets/src/getTransaction.ts
snippets/src/parseAccountFlags.ts
snippets/src/paths.ts
snippets/src/reliableTransactionSubmission.ts
src/broadcast.ts
src/client/broadcast.ts
src/client/index.ts
src/index.ts
test/broadcast-client-test.ts
test/client/computeLedgerHash/index.ts
test/client/constructor/index.ts
test/client/prepareSettings/index.ts
test/connection-test.ts
test/integration/integration-test.ts
test/ripple-client-test-private.ts
test/ripple-client-test.ts
test/setup-client-web.ts
test/setup-client.ts

Title says it all. This PR also renames `ClientBroadcast` to `BroadcastClient`.
xrpl.js v2.0 client revamp
We're moving all the methods that don't require a client outside of the client, so you should no longer ever need a client without a URI.
Edited tests to pass.

Edit Client constructor to take a server URI

---

test/broadcast-client-test.ts
test/client/getFee/index.ts
test/client/prepareCheckCancel/index.ts
test/client/prepareCheckCash/index.ts
test/client/prepareCheckCreate/index.ts
test/client/prepareEscrowCancellation/index.ts
test/client/prepareEscrowCreation/index.ts
test/client/prepareEscrowExecution/index.ts
test/client/prepareOrder/index.ts
test/client/prepareOrderCancellation/index.ts
test/client/preparePayment/index.ts
test/client/preparePaymentChannelClaim/index.ts
test/client/preparePaymentChannelCreate/index.ts
test/client/preparePaymentChannelFund/index.ts
test/client/prepareSettings/index.ts
test/client/prepareTicket/index.ts
test/client/prepareTransaction/index.ts
test/client/prepareTrustline/index.ts
test/client/request/index.ts
test/client/sign/index.ts
test/mock-rippled.ts

Improve https://github.com/ripple/ripple-lib/pull/1551 to be slightly more concise
This idea came to mind while I was reviewing https://github.com/ripple/ripple-lib/pull/1551
Before:
A standalone `addRippledResponse` function
After:
We have an `addResponse` method on the mock server object, which is a little cleaner and saves us a line of code (no need to import)
Existing tests pass

refactor: addResponse method on mock server object

---

test/broadcast-client-test.ts
test/client/getFee/index.ts
test/client/prepareCheckCancel/index.ts
test/client/prepareCheckCash/index.ts
test/client/prepareCheckCreate/index.ts
test/client/prepareEscrowCancellation/index.ts
test/client/prepareEscrowCreation/index.ts
test/client/prepareEscrowExecution/index.ts
test/client/prepareOrder/index.ts
test/client/prepareOrderCancellation/index.ts
test/client/preparePayment/index.ts
test/client/preparePaymentChannelClaim/index.ts
test/client/preparePaymentChannelCreate/index.ts
test/client/preparePaymentChannelFund/index.ts
test/client/prepareSettings/index.ts
test/client/prepareTicket/index.ts
test/client/prepareTransaction/index.ts
test/client/prepareTrustline/index.ts
test/client/request/index.ts
test/client/sign/index.ts
test/connection-test.ts
test/fixtures/rippled/account-objects.js
test/fixtures/rippled/index.js
test/fixtures/rippled/server-info-high-load-factor.json
test/mock-rippled.ts
test/ripple-client-test.ts
test/utils.ts

This PR makes it more intuitive to write tests, by beginning the process of moving fixtures closer to the tests they work with. Now, you can add a fixture in the test itself instead of needing to dig around in `mock-rippled.ts`.
This is just a sample of what the result will be like (just did `account_info`, `account_objects`, and `server_info` for now), because I wanted to get feedback before doing everything.
The most relevant file is `mock-rippled.ts`; the rest of the files are mostly scattering the changes across the tests.
Making it easier to write/modify tests
Tests still pass.
* Move the rest of the mocks

refactor: moves fixtures closer to tests

---

src/client/connection.ts
src/client/index.ts
test/connection-test.ts
test/mock-rippled.ts

When a test failed because of an error in its code, the `afterEach` script would fail because the websocket wouldn't properly disconnect. This fixes that problem. A different error is thrown, but it's also pretty descriptive, so it's fine.
test cleanup
CI passes.

fix: websocket wouldn't close properly on erroring test

---

docs/index.md
docs/src/accountSetFlags.md.ejs
src/api.ts

Exports `txFlags` and `accountSetFlags` on both `api` instance and on `RippleAPI` class.
Fixes #1483 
Fixes #1568 
Exports both `txFlags` and `accountSetFlags` in the same manner on the RippleAPI class.
Also adjusts the documentation formatting and builds documentation.

Correctly export txFlags and accountSetFlags

---

.eslintrc.js
tsconfig.eslint.json

A couple of linter rules were moved to the @xrpl/typescript-style repo, and so they can be removed here. Also adds linting for `eslintrc.js`

build: remove linter rules already in base config

---

src/client/index.ts
src/index.ts
src/ledger/autofill.ts
src/models/transactions/accountSet.ts
src/models/transactions/offerCreate.ts
src/models/transactions/payment.ts
src/models/transactions/paymentChannelClaim.ts
src/models/transactions/transaction.ts
src/models/transactions/trustSet.ts
src/models/utils/index.ts
test/models/payment.ts
test/models/utils.ts

Cleans up how flags are named.
Replaces `<TxType>FlagEnum` with `<TxType>TransactionFlags`, and exports flag enums. This makes it such that a client trying to access a flag value would use `OfferCreateTransactionFlags.tfPassive` instead of `OfferCreateFlagsEnum.tfPassive`.
It also adds `AccountSetTransactionFlags`, which is import *AND* different from `AccountSetFlags`

feat: cleanup flag naming

---

src/wallet/signer.ts
test/wallet/signer.ts

Encode multisign's return instead of just returning the Transaction object 
This change was inspired by using multisign and realizing the Transaction shouldn't be modified after combining signatures. (All Transaction modifications should happen before then)
Before multisign returned a Transaction object, now it encodes that object before returning.
CI Passes

Change multisign to return an encoded transaction instead of a Transaction object

---

test/integration/integration.ts

Changing the return type of multisign accidentally broke the integration tests. 
Integration + CI passes

Fix multisign integration test

---

src/wallet/index.ts
test/wallet/index.ts

It seemed odd to have to use .fromSeed(...) on variables named 'secret', even if it works. This makes more intuitive sense.
Added a Wallet.fromSecret(...) method to generate a wallet which just uses fromSeed underneath.
Added a CI tests to ensure the wallet works as expected.

Add Wallet.fromSecret(...) as an alias for Wallet.fromSeed(...)

---

.eslintrc.js
src/client/requestManager.ts
src/models/methods/baseMethod.ts
src/models/methods/index.ts
src/models/transactions/transaction.ts
src/wallet/index.ts
test/client/subscribe.ts
test/integration/integration.ts
test/integration/requests/utility.ts
test/mockRippled.ts
test/models/accountDelete.ts
test/models/accountSet.ts
test/models/checkCancel.ts
test/models/checkCash.ts
test/models/checkCreate.ts
test/models/depositPreauth.ts
test/models/escrowCancel.ts
test/models/escrowCreate.ts
test/models/escrowFinish.ts
test/models/offerCancel.ts
test/models/offerCreate.ts
test/models/paymentChannelClaim.ts
test/models/paymentChannelCreate.ts
test/models/paymentChannelFund.ts
test/models/ticketCreate.ts
test/models/trustSet.ts

Adds an error response object to account for error responses. Also ran the auto-linter.
We didn't have an error response object. It's not super necessary since the client throws an error if an error response is received, but it's still good to have one.
CI passes.

refactor: adds error response object

---

src/client/index.ts
src/utils/index.ts

The ripple-address-codec methods don't need to be exported as static methods on the client - they don't require a network connection, and they really are utils.
Happy to also delete them if you'd rather that they export them from ripple-address-codec.
xrpl.js cleanup
CI passes.

refactor: move address-codec methods from client to utils

---

test/localIntegrationRunner.html
webpack.config.js

This PR webpacks all the integration test files for testing, and runs all of the tests on the browser.
Because we started using multiple files for integration tests, the browser tests did not pick up those files, and continued to only run the tests on the one file.
CI passes. All the integration tests run on the browser.
This is not the best code, and needs to be revamped a bit before we officially publish 2.0. But it's good enough for now.
* The script tags in `localIntegrationRunner.html` should be dynamically added
* The files in `testCompiledForWeb` should be properly nested in folders
* Browser tests should print better debugging info in the CLI

fix: run browser tests on all integration tests

---

src/client/requestManager.ts
test/client/submitSignedTransaction.ts
test/connection.ts
test/mockRippled.ts
test/testUtils.ts

There was a bug in `RequestManager` where if someone hand-inputted an ID into their request, they could have 2 requests with the same IDs. This PR fixes that (and improves handling of string request IDs).
@ledhed2222 pointed out a bug
CI passes.

fix: disallow two pending requests with the same id

---

webpack.config.js

Adds the `mode: production` to webpack config to silence a warning.

build: silence warning while webpacking

---

package.json

On npm - https://www.npmjs.com/package/xrpl - the Repository was wrong (because I previously published a "placeholder" package which had the wrong respository.url)
Renaming ripple-lib to xrpl.js

Release xrpl.js 1.10.0 - Update repository.url

---

src/wallet/generateFaucetWallet.ts

Cleans up how `getFaucetWallet` was computing starting balance.
Previously, if the xrp balance was undefined, starting balance was set to be zero. We can clean this up into one try/catch block, with the starting balance assumed to be zero if an error is thrown.

refactor: clean up getFaucetWallet starting balance

---

src/sugar/autofill.ts
src/sugar/orderbook.ts
src/wallet/generateFaucetWallet.ts
test/integration/transactions/paymentChannelClaim.ts
test/integration/transactions/paymentChannelFund.ts
test/integration/utils.ts

There were a couple of places where we were assuming the default value for `ledger_index` was validated. This PR explicitly specifies `ledger_index: validated` in those places.

fix: set ledger_index to `validated`

---

src/wallet/generateFaucetWallet.ts
test/integration/generateFaucetWallet.ts

This PR removes `undefined` from the `generateFaucetWallet()` method's type signature.
There is not a situation where `generateFaucetWallet()` should return an `undefined`.  As such, we can change `Promise<Wallet | undefined>` into `Promise<Wallet>`.

fix: remove undefined from generateFaucetWallet return type

---

src/wallet/generateFaucetWallet.ts

This PR converts the `Uint8Array` to a `Buffer`
`requests` in NodeJS expects the body to be in the form of a Buffer. We use `Buffer.from()` to convert the Array into a buffer.

fix: convert uint8Array to Buffer

---

package.json

Adds a browser field to package.json.
When `xrpl.js` was being used in react, the react polyfills were attempting to use ws in the browser, which doesn't work. The `wsWrapper.js` specifies that in the browser, use `client/wsWrapper.js` instead of ws.

fix: adds browser field to package.json

---

package-lock.json
package.json

Increases version to `2.0.0-beta.4`, including the fix for the `wsWrapper` issues we were having. 
Issue first seen in #1691, and later in some react testing we were doing locally. This specifies that when running in the browser, xrpl.js should use `wsWrapper.js` instead of `ws`.

build: prepare for beta.4

---

README.md

ripple-lib has been deprecated in favor of xrpl.js, but it still has a lot of existing users/projects. This PR updates the README to link to the ripple-lib reference documentation

README - update link to reference docs

---

packages/ripple-address-codec/package.json
packages/ripple-binary-codec/package.json
packages/ripple-keypairs/package.json
packages/xrpl/package.json

Remove npm requirement in `engines` package.json entry from individual packages.
Users who have an `npm` version below v7 get errors when trying to install `xrpl.js`. `engines` requirements for `npm` should be removed out of individual packages and only set to the top level private package, so only contributors have that requirement. 
All existing tests pass.

remove engines requirement for npm from individual packages

---

packages/ripple-binary-codec/src/types/currency.ts
packages/ripple-binary-codec/test/hash.test.js

This PR fixes an issue where some tokens with non-traditional currency codes weren't being encoded properly; they were being encoded as `XRP` for some reason. 
Issue with data ingestion from the ledger (calculated tx hash wasn't equal to the rippled-calculated hash)
Added test. CI passes.

fix: encoding issue with encoding non-traditional currency codes

---

packages/ripple-binary-codec/HISTORY.md
packages/xrpl/HISTORY.md

Move the release notes for the UNLModify fix into ripple-binary-codec since that's where the code changed. 
Accidentally put this fix into the xrpl HISTORY.md, but it belongs in the ripple-binary-codec HISTORY.md.
Manually checked where the corresponding code change was, and it was in ripple-binary-codec

Move UNLModify fix to proper History.md file

---

package-lock.json
packages/xrpl/HISTORY.md
packages/xrpl/package.json
packages/xrpl/src/sugar/submit.ts
packages/xrpl/test/integration/requests/submit.ts

Add validation for RippledError when a tx has not been validated and the lastLedgerSequence hasn't passed.
I came across 2 transactions where the `submitAndWait` function failed to get the status of the transaction when the transaction is still in queue and tx command is not able to find it reason being it is not processed and hence doesn't reflect on rippled databases.
Now, if the transaction is not found, we wait for it to show up(assuming it is going to be processed) or wait for the LastLedgerSequence to pass.
Added test to demonstrate how it is reproduced. Passes CI tests.

fix: `txnNotFound` error

---

packages/xrpl/src/models/methods/subscribe.ts
packages/xrpl/src/models/methods/tx.ts
packages/xrpl/src/models/transactions/common.ts

Adds non-canonical fields which are returned on requests, but are not normally part of transactions on the ledger.
See #1892 
* Before `date` and `hash` were missing from these models even though the requests/subscriptions returned them.
CI Passes

Add missing fields to TxSubscription and Tx requests

---

packages/ripple-binary-codec/package.json

On the [ripple-binary-codec npm package page](https://www.npmjs.com/package/ripple-binary-codec), the the second GitHub link was broken. This fixes it.
Reported via @mvadari

[ripple-binary-codec] package.json - fix homepage link

---

packages/ripple-binary-codec/HISTORY.md
packages/ripple-binary-codec/src/types/currency.ts
packages/ripple-binary-codec/test/hash.test.js

Fixes ISO when parsing currency code.
Storm importer reported a bug where ripple-binary-codec encode/decode wasn't properly working.
Root cause is the parsing logic inside Currency constructor doesn't set ISO field correctly.
Added tests to verify the bug is resolved.

[ripple-binary-codec] fix ISO when parsing currency code

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/transactions/trustSet.ts

This PR changes Type on TrustSet interface property LimitAmount from Amount (string/object) to IssuedCurrencyAmount(object)
The reason why I made this PR is because I encountered an error while working with data from the TrustSet transaction in the TypeScript environment. 
If you tried to access data from the LimitAmount object on TrustSet transaction, like value, issuer, or currency. You would get a type error that this property does not exist on type Amount (type string). This is because TrustSet transaction was using universal Amount type and not specific type like IssuedCurrencyAmount.
According to [xrpl.org](https://xrpl.org/trustset.html#trustset) docs, TrustSet's LimitAmount property should be an Object, not string, which makes me even more sure with this change.
I tested this …

[Small Type error Fix]TrustSet LimitAmount Type changed

---

packages/xrpl/src/models/common/index.ts
packages/xrpl/src/models/methods/accountTx.ts
packages/xrpl/src/models/methods/baseMethod.ts
packages/xrpl/src/models/methods/norippleCheck.ts
packages/xrpl/src/models/methods/subscribe.ts
packages/xrpl/src/models/methods/transactionEntry.ts

This allows you to access the date, hash, and ledger_index fields on tx responses.
Follow up to #1768.
These fields are available when retrieving transactions from a validated ledger, e.g. with the 'account_tx' command.
The returned txs have date, hash, and ledger_index fields.
Without this fix, TypeScript users need to apply workarounds such as type assertion on the returned objects (e.g. `as any`)

Add tx info which is only available in requests

---

packages/ripple-address-codec/HISTORY.md
packages/ripple-address-codec/src/index.ts
packages/xrpl/test/utils/deriveXAddress.ts

`deriveXAddress` should have the same behavior for `null` as it does for `false`. 
In response to #1872 
Added a unit test for it.

Fix deriveXAddress null behavior

---

packages/ripple-keypairs/HISTORY.md
packages/ripple-keypairs/src/utils.ts
packages/ripple-keypairs/test/utils-test.js

`hexToBytes` uses the `BN` library, but `BN.toArray` intentionally produces `[0]` rather than `[]` for a zero buffer, even when requesting output of zero length. This may make sense for BigNum buffers, but not for byte strings.
This change fixes that by special-casing zero-length input to `[]`.
- Related to https://github.com/XRPLF/xrpl.js/pull/1975
- Before: `hexToBytes('')` produced `[0]`
- After: `hexToBytes('')` produces `[]`
I added a unit test case.

fix(ripple-keypairs): hexToBytes should produce [] for empty input, not [0]

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/common/index.ts

Add missing filter types in AccountObjectType.
User reported an [issue](https://github.com/XRPLF/xrpl.js/issues/1902) with missing filter types in AccountObjectTypes
Verified all tests pass.

add missing filter types in AccountObjectType

---

test/fixtures/rippled/account-set-with-deleted-node.json
test/settings.ts

Follow up to #1907 to add a test for the change.
I manually reverted the changes from #1907 to see if this test case fails, then re-added the change and checked that the test now passes. (The test case uses real rippled data from the ledger mentioned in #1926 where this issue was originally raised, so it should parse it successfully).

Add test for parseSettings on AccountSet with deleted node

---

packages/xrpl/HISTORY.md
packages/xrpl/src/client/BroadcastClient.ts

Currently it's not functional, and we decided against building it out when xrpl-client already exists and the goal of reliability could be better implemented via reconnect logic + using a reliable endpoint like xrpl.ws. 
See issue: https://github.com/XRPLF/xrpl.js/issues/1925
None

Deprecate BroadcastClient

---

packages/ripple-keypairs/HISTORY.md

We were accidentally releasing changed versions without any changes, so our HISTORY was out of date. This corrects that.

Fix ripple-keypair HISTORY.md version

---

packages/xrpl/HISTORY.md
packages/xrpl/src/sugar/submit.ts

When `submitAndWait` failed with no error message it accidentally triggers a TypeError instead of displaying the preliminary result.
In response to the integration test for `submitAndWait` occasionally failing for no apparent reason. (Ex. On a docs only change)
This is the error which would occur in the tests:
```
1) client.submitAndWait
xrpl:        submitAndWait an unsigned transaction:
xrpl:      TypeError: Cannot read properties of undefined (reading 'error')
xrpl:       at /home/runner/work/xrpl.js/xrpl.js/packages/xrpl/src/sugar/submit.ts:2:5564
xrpl:       at Generator.next (<anonymous>)
xrpl:       at /home/runner/work/xrpl.js/xrpl.js/packages/xrpl/src/sugar/submit.ts:2:1415
xrpl:       at new Promise (<anonymous>)
xrpl:       at __awaiter (src/sugar/submit.ts:2:586)
xrpl: …
```

Fix reliable submission masking legitimate error with type error

---

packages/xrpl/HISTORY.md
packages/xrpl/src/client/connection.ts

When an exception is raised during the websocket connection, it can cause a disconnect with no error code, which can then cause an infinite series of reconnect + errors.
In response to #1825 
Before:
(Errors keep repeating infinitely)
After:
(Error happens once with a more descriptive error message)
Manually reproduced using @mDuo13's steps to reproduce and verified it only disconnected once after the changes.

Fix browser infinite disconnect if exception raised during 'connected'

---

packages/ripple-binary-codec/HISTORY.md
packages/ripple-binary-codec/src/types/st-object.ts
packages/ripple-binary-codec/test/signing-data-encoding.test.js

Add a clear error message when trying to encode invalid transactions.
The error message if you put in an incorrect TransactionType is very hard to understand/debug.
In response to https://github.com/ripple/ripple-binary-codec/issues/126
And the migrated issue: https://github.com/XRPLF/xrpl.js/issues/1808
CI passes + added a test case for this new error.

Add better error for trying to encode invalid transactions

---

packages/xrpl/HISTORY.md
packages/xrpl/src/Wallet/fundWallet.ts
packages/xrpl/test/integration/fundWallet.ts

Lets fundWallet infer the NFT Devnet faucet when the client is connected to NFT Devnet.
It's not easy to find the url for the NFT Devnet, and it's really common to want to generate a new wallet for testing purposes on the NFT Devnet, so this seems like a nice quality of life change. (If NFT Devnet turns off, their client won't be pointed to it anyway, and we can then remove this at any point)
CI Passes

Add NFT Devnet as an inferable faucet 

---

packages/xrpl/HISTORY.md
packages/xrpl/src/Wallet/index.ts
packages/xrpl/src/Wallet/rfc1751.ts
packages/xrpl/test/wallet/index.ts

Updates Wallet.fromMnemonic to have better validation checks, work with react-native on android, and 
In response to a couple issues raised surrounding the function #2042 and #2044. (Exact changes made as a result are listed below)
* There are now validation checks on whether an encoding is valid in BOTH bip39 and rfc1751 encodings (So should not be possible to end up in a situation like #2042)
* Lowercase words now work with rfc1751 encoding (Fixes #2042) 
* It wasn't working in react-native for Android (Fixes #2044) 
* Added more tests for common mistakes people could make (And ensured that they properly error)
CI Passes

Fix Wallet.fromMnemonic 

---

packages/xrpl/src/client/connection.ts

Allow users to customize the headers field in the client connection to provide api keys.
In response to #2034 
You can now add a custom header if you want.
CI passes

Allow customized headers

---

packages/xrpl/HISTORY.md
packages/xrpl/src/sugar/submit.ts

Provides more context when an unknown error happens during the submitAndWait function
The integration test for `submitAndWait` is being flaky and giving this error, but it's not possible to debug because the message is undefined. This should allow us to debug it if it happens in the future, in addition to providing a better experience for folks running into unexpected exceptions using `submitAndWait`.
Added more information to the exception message.
CI Passes

Make the unknown submitAndWait error more verbose

---

packages/xrpl/HISTORY.md
packages/xrpl/src/utils/index.ts

Exports the `verify` function from `ripple-binary-codec` so it can be used in web apps.
Trying to use the function in a webapp, but ripple-keypairs doesn't have webpacking.
CI Passes

feat: Export verify

---

README.md

A guide for using React with xrpl.js.  Specifically this guide covers using `react-app-rewire` alongside `create-react-app`.  
Webpack 5 broke how polyfills are applied.  This guide details a workaround
Additional guides may need to be created based on feedback about which build tools the community is using.

docs(react): Add guide for create-react-app

---

packages/xrpl/snippets/src/setRegularKey.ts

Code snippet for regular wallet did not do as intended. Fixed one liner to make it so tx was signed by regular key wallet and not original wallet as a normal tx would.
Snippet was misleading (comments stated one thing, code did another)
Edited one line in snippet to sign with reg key rather than wallet
Ran snippet in separate window

fix: corrected snippet to show regular key works

---

packages/xrpl/HISTORY.md
packages/xrpl/src/Wallet/index.ts
packages/xrpl/test/wallet/index.ts

add a check in `wallet.sign()` to see if fields in Memos are hex values, if not, throw a specific error message like "MemoType field must be a hex value". 
link to issue https://github.com/XRPLF/xrpl.js/issues/1790
- [ X] Bug fix (non-breaking change which fixes an issue)
added three unit tests case

add Memos hex value check in Wallet.sign

---

packages/xrpl/src/sugar/submit.ts

Changed reliable submission ledger close time from 4 to 1 to enhance transaction speed
An example of where that might actually make the function run faster in a normal operation: according to [livenet.xrpl.org](http://livenet.xrpl.org/) a normal ledger on mainnet closes every 4.068 seconds right now. If the relsub method checks after 4 seconds, it would have to wait another 4 seconds before checking again, and take 8 seconds to finish, even if the transaction was validated after 4.068 seconds. If we switch to checking every 1 second, then it would take 5 seconds to finish.
CI tests

feat: shorten ledger close time

---

packages/xrpl/src/utils/getBalanceChanges.ts

NormalizedNode interface has miss typed key definition "PreviouTxnLgrSeq" now renamed to "PreviousTxnLgrSeq"
No effect.
Please re-run tests before merging.

Typo fix in getBalanceChanges.ts

---

packages/xrpl/.eslintrc.js
packages/xrpl/HISTORY.md
packages/xrpl/package.json
packages/xrpl/src/client/WSWrapper.ts
packages/xrpl/src/models/methods/subscribe.ts

This change ignores `https-proxy-agent` from browser environments in `package.json`, mirroring the existing content in https://github.com/XRPLF/xrpl.js/blob/main/packages/xrpl/webpack.config.js#L59
With some effort in our Vite.js based project, we were able to polyfill node dependencies to resolve [this known issue](https://github.com/XRPLF/xrpl.js/issues/1691#issuecomment-1202076652).
However, this fix did not extend to our Cypress test environment.  With a working Vite configuration, running Cypress tests yields:
```
Error: Build failed with 2 errors:
node_modules/https-proxy-agent/dist/agent.js:15:38: ERROR: Could not resolve "net"
node_modules/https-proxy-agent/dist/agent.js:16:38: ERROR: Could not resolve "tls"
at failureErrorWithLog (/node_modules/esbuild/lib/main.js:1566:15)
```
To …

Ignore `https-proxy-agent` dependency in browser environments

---

CONTRIBUTING.md

Currently the release instructions lacks the steps for editing HISTORY.md to reflect the version changes, this PR adds the step to CONTRIBUTING.md. 
- [X ] Documentation Updates

add editing HISTORY.md step to release insturctions

---

.github/workflows/nodejs.yml
packages/xrpl/test/connection.test.ts

Connection.ts had a broken test `with proxy` when using node 18.
The error: 
```
1) Connection
with proxy:
Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/jacksonmills/Documents/xrpl-js-6/xrpl.js/packages/xrpl/test/connection.test.ts)
at listOnTimeout (node:internal/timers:564:17)
at processTimers (node:internal/timers:507:7)
```
Changed `localhost` to `127.0.0.1` following this workaround: https://github.com/node-fetch/node-fetch/issues/1624
Run tests locally & get a code reviewer to try the same with Node 18
Turn on Node 18 CI

Fix broken test in connection.ts for node 18 and add node 18 testing

---

packages/xrpl/src/Wallet/defaultFaucets.ts
packages/xrpl/test/integration/fundWallet.test.ts
packages/xrpl/test/wallet/fundWallet.test.ts

XLS20-sandbox (NFT Devnet) is no longer needed since mainnet has the amendment enabled.
Tests are failing because it's not up.
* Add a TODO where it's still in the codebase
* Remove it entirely from tests.
Remove it from the codebase once it's fully decomissioned.

Remove xls20-sandbox tests

---

packages/xrpl/src/models/common/index.ts
packages/xrpl/src/models/methods/accountObjects.ts
packages/xrpl/src/models/methods/ledgerEntry.ts

This PR:
* Alphabetizes the subcommands in `ledger_entry`
* Moves the subtype `AccountObjectsType` from `models/common` to `accountObjects.ts`, which is the only place it's used in the repo.
Better code organization
CI passes.

refactor: alphabetize `ledger_entry` commands and reorganize `account_objects`

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/AccountRoot.ts
packages/xrpl/src/models/transactions/accountSet.ts
packages/xrpl/test/models/accountSet.test.ts
packages/xrpl/test/models/utils.test.ts

Adding client library support for the `disallowIncoming` amendment being proposed soon: https://github.com/XRPLF/rippled/pull/4336
Adds 4 more account flags for disallowing incoming objects on the ledger.
* Adds `lsfDisallowIncomingNFTokenOffer
CI Passes

Add support for disallowIncoming flags

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/AccountRoot.ts
packages/xrpl/src/models/transactions/accountSet.ts
packages/xrpl/test/models/utils.test.ts

`lsfDisallowIncomingNFTOffer` to `lsfDisallowIncomingNFTokenOffer`
`asfDisallowIncomingNFTOffer` to `asfDisallowIncomingNFTokenOffer`
Related to XRPLF/rippled#4442

fix: rename DisallowIncoming flag for NFTs

---

.github/workflows/codeql-analysis.yml

v1 was deprecate in January 18th, 2023 and the github ssh update likely broke v1.

chore: bump codeql-analysis

---

.vscode/settings.json
packages/xrpl/HISTORY.md
packages/xrpl/src/Wallet/index.ts
packages/xrpl/src/models/transactions/transaction.ts
packages/xrpl/test/models/trustSet.test.ts
packages/xrpl/test/wallet/index.test.ts

This PR removes the `decode(encode(tx)) == tx` check in the wallet signing process and moves the other validation checks that happened as a part of signing to `validate`.
It requires a bunch of edge case checks and it's easy to get tripped up with an error, but it doesn't actually find bugs.
CI passes. Minorly fixed tests due to moving stuff around (one test was flat out bad).

fix: remove tx serialization check

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/methods/accountInfo.ts

The `account_info` response type had `signer_lists` under `result`, but it's actually under `account_data`.
I ran into this issue when writing some integration tests.
Matches actual rippled responses, and works with an `account_info` request that asks for the signer list.

fix: fix the location of `signer_lists` in the `account_info` response

---

.github/workflows/codeql-analysis.yml
.github/workflows/nodejs.yml
CONTRIBUTING.md
README.md

Title says it all. I also updated our linter and browser tests to use v16 instead of now-deprecated v14.
node v20 was just released
CI passes with node 20.

feat: add support for node v20

---

packages/xrpl/src/sugar/submit.ts
packages/xrpl/test/client/submit.test.ts

Update `isSigned()` null check to handle multi-signed transactions.
Adds a unit test for verifying a multi-signed transaction is signed.

update isSigned null check to handle multi-signed transactions

---

packages/xrpl/test/integration/README.md

Inside integ tests README, add missing `run` in npm commands for running integ tests
Integ tests now run when copy/pasting npm commands from integ tests README

fix README for integ tests

---

.ci-config/rippled.cfg

Added instructions for adding amendments which aren't enabled on devnet yet for integration testing. 
Sometimes amendments take a while to be added to devnet, but we still want to test them.
CI Passes

Improve instructions for updating integration test docker container config

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/methods/tx.ts
packages/xrpl/src/sugar/submit.ts

Make Tx command response possible by specifying a transaction.
- [ x] Documentation Updates

Add generics of TransactionType for TxResponse

---

package-lock.json
packages/ripple-keypairs/HISTORY.md
packages/ripple-keypairs/package.json
packages/xrpl/package-lock.json
packages/xrpl/package.json

Lerna didn't release an update to ripple-keypairs because the last beta release used the name 1.2.0, which caused a collision with our updated version. So, we're updating the release of ripple-keypairs to be 1.3.0 to avoid that.
Above says it all.

Retry releasing ripple-keypairs

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/methods/accountChannels.ts
packages/xrpl/src/models/methods/accountCurrencies.ts
packages/xrpl/src/models/methods/accountInfo.ts
packages/xrpl/src/models/methods/accountLines.ts
packages/xrpl/src/models/methods/accountNFTs.ts
packages/xrpl/src/models/methods/accountObjects.ts
packages/xrpl/src/models/methods/accountOffers.ts
packages/xrpl/src/models/methods/accountTx.ts
packages/xrpl/src/models/methods/baseMethod.ts
packages/xrpl/src/models/methods/bookOffers.ts
packages/xrpl/src/models/methods/depositAuthorized.ts
packages/xrpl/src/models/methods/gatewayBalances.ts
packages/xrpl/src/models/methods/ledger.ts
packages/xrpl/src/models/methods/ledgerData.ts
packages/xrpl/src/models/methods/ledgerEntry.ts
packages/xrpl/src/models/methods/nftBuyOffers.ts
packages/xrpl/src/models/methods/nftHistory.ts
packages/xrpl/src/models/methods/nftInfo.ts
packages/xrpl/src/models/methods/nftSellOffers.ts
packages/xrpl/src/models/methods/ripplePathFind.ts
packages/xrpl/src/models/methods/transactionEntry.ts

- Add `ledger_hash` and `ledger_index` to `account_nfts`, `nft_buy_offers`, and `nft_sell_offers` requests.
- Add `nft_page` to `ledger_entry` request.
- Create `LookupByLedgerRequest` to clean up `ledger_hash` and `ledger_index` which are optional on most request objects.
Closes #2135

feat: cleanup types and add missing request fields

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/methods/accountInfo.ts
packages/xrpl/src/models/methods/index.ts

The `account_flags` field was added to the `account_info` response for `rippled@1.11.0`

feat(types): define new `account_flags` field

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/FeeSettings.ts
packages/xrpl/src/models/ledger/index.ts

Adds the new fields for `XRPFees` amendment and id for the `FeeSettings` singleton ledger entry.
Closes #2219

feat(types): Update `FeeSettings` and add id

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/SignerList.ts

`SignerEntry` on `SignerList` (LedgerEntry) was missing `WalletLocator`.
This was found while trying to use types on the xrpl.org explorer.

fix(types): `SignerList` was missing `WalletLocator`

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/Amendments.ts
packages/xrpl/src/models/ledger/FeeSettings.ts
packages/xrpl/src/models/ledger/NegativeUNL.ts
packages/xrpl/src/models/ledger/index.ts

Add an id for `NegativeUNL` and `Amendments` which are singleton objects.

feat: expose LedgerEntry singletons

---

packages/xrpl/src/models/transactions/signerListSet.ts
packages/xrpl/test/integration/transactions/signerListSet.test.ts

signerquorum field has to be 0 and the signerentires field has to be undefined

Enable the removal of a signer list

---

packages/xrpl/test/integration/transactions/escrowCancel.test.ts
packages/xrpl/test/integration/transactions/escrowFinish.test.ts
packages/xrpl/test/integration/utils.ts

fix: escrow finish and cancel integration

---

packages/ripple-binary-codec/src/serdes/binary-parser.ts
packages/ripple-binary-codec/test/binary-parser.test.js

Found a tiny assertion typo while reviewing the merge in #2337
This assertion was previously 
```
assert.ok(0 < n && n <= 4, 'invalid n')
```
And since the new version needs to invert the condition (since it throws when true instead of passing when true) the `&&` should be a `||`. 
Link to the line in the 2.x branch: https://github.com/XRPLF/xrpl.js/blob/bd46f1960499974d245e51ba45490cccba9e4517/packages/ripple-binary-codec/src/serdes/binary-parser.ts#L73C1-L74C1
CI Passes

fix: Fix invariant assertion in binary-codec

---

packages/xrpl/src/client/index.ts

Fixes typo in typedoc example comment.
The documentation describing the client.on method provides an example where the 'transactions' event stream is listened to. This is a mistake as it should not be plural. This patch fixes it to demonstrate listening on the 'transaction' event stream
Copy the example and make sure it works! :smile:

Fix typo in documentation: on('transactions') -> on('transaction')

---

README.md

Unique setup links on docs are broken because they are relative links which aren't generated in js.xrpl.org, changed the links to guide back to github pages. 
- [X ] Bug fix (non-breaking change which fixes an issue)

fix docs broken links 

---

packages/ripple-address-codec/HISTORY.md
packages/ripple-binary-codec/HISTORY.md
packages/ripple-keypairs/HISTORY.md
packages/xrpl/HISTORY.md
packages/xrpl/src/errors.ts
packages/xrpl/test/client/errors.test.ts

- Remove `util` from bundle by switching `inspect` to `JSON.stringify`
- Update `HISTORY.md` with latest 3.0 changes

feat: remove `util` polyfill and fix `HISTORY.md`

---

packages/xrpl/test/wallet/index.test.ts

Adds a test for using ED25519 as a custom algorithm to `walletFromSecretNumbers`
Now that the underlying issue is fixed allowing users to specify which algorithm they want, we can re-add this test.
CI Passes

Re-add the `walletFromSecretNumbers` custom algorithm test

---

packages/xrpl/src/models/common/index.ts

Makes the interface of `XRP` and `IssuedCurrency` compatible to avoid casting when referencing `Currency.issuer`
Found when trying to access `Currency.issuer` in the explorer while trying to add the support for `AMMDelete`
Manually via type checking when experimenting with types in the explorer.

fix: Avoid casting when using `Currency` type for AMM objects

---

packages/ripple-address-codec/HISTORY.md
packages/ripple-binary-codec/HISTORY.md
packages/ripple-keypairs/HISTORY.md
packages/xrpl/HISTORY.md

This was missed when I did #2435 which led to `ripple-address-codec` and `ripple-keypairs` not being released.

doc: update HISTORY.md with source-map fix

---

package-lock.json
packages/ripple-address-codec/package.json
packages/ripple-binary-codec/package.json
packages/ripple-keypairs/package.json
packages/secret-numbers/package.json
packages/xrpl/package.json

This is done by properly deleting all build files.
`package-lock.json` was due to it not reflecting the license of @xrplf/secret-numbers.  This was fixed by running `npm i`.

fix: remove need to --force builds + cleanup

---

packages/xrpl/src/models/ledger/AMM.ts
packages/xrpl/src/models/ledger/AccountRoot.ts
packages/xrpl/src/models/ledger/index.ts
packages/xrpl/src/models/methods/accountObjects.ts
packages/xrpl/src/models/methods/ammInfo.ts

- Add AMM to BaseLedgerEntry and AccountObject types.
- Add `amm_account` to `amm_info` request
- Add `AMMID` to `AccountRoot`
All tests pass.

fix: add AMM to BaseLedgerEntry and AccountObject types

---

packages/xrpl/src/sugar/autofill.ts

We decided to keep the version check because not everyone operates with the same version of rippled, even if there is wide adoption for newer versions.
Closes #2339
N/A

docs: Remove TODO with rippled version check

---

karma.config.js
packages/ripple-address-codec/HISTORY.md
packages/ripple-address-codec/karma.config.js
packages/ripple-address-codec/package.json
packages/ripple-address-codec/test/index.test.ts
packages/ripple-address-codec/test/utils.test.ts
packages/ripple-address-codec/test/webpack.config.js
packages/ripple-address-codec/test/xrp-codec.test.ts
packages/secret-numbers/karma.config.js
packages/secret-numbers/package.json
packages/secret-numbers/test/webpack.config.js
packages/xrpl/karma.config.js
packages/xrpl/package.json
packages/xrpl/test/webpack.config.js
weback.test.config.js

Update tests to use jasmine compatible functions.
This means changing `test` to `it`, `toStrictEqual` to `toEqual` (which is still strict), `toThrowError` to `toError`, and updating the param for toError to pass an `Error` object.
Additionally the test webpack and karma configs were refactored to reuse code between packages.
Having tests run in the browser as well checks for minimum viable bundling setup.

test: run address-codec tests in the browser

---

.github/dependabot.yml

Changes the dependabot interval to weekly
Closes #2394 - There's unfortunately no option for twice a month, but weekly should be about as good. Anything which keeps getting re-opened we can use the dependabot commands to indicate our preferences for when to be notified about changes. (E.g. on the next major version)
N/A

Update the dependabot interval to weekly

---

packages/ripple-address-codec/package.json
packages/ripple-binary-codec/package.json
packages/ripple-keypairs/package.json
packages/xrpl/package.json

Since we've deprecated ripple-lib, we should make xrpl.js show up when they search for that instead. 
Helping to make xrpl.js more discoverable, especially for people who knew older names for the library.
Inspection + Search npm for ripple-lib after the next release and see if this shows up.

docs: Update xrpl.js keywords to make it easier to find

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/utils/flags.ts
packages/xrpl/test/models/NFTokenCreateOffer.test.ts
packages/xrpl/test/models/NFTokenMint.test.ts

You can now `NFTokenMint` and `NFTokenCreateOffer` transactions with `Flags` set to a map like other transactions with flags do.
ex. `{ tfSellNFToken: true }`
This also cleans up the code around choosing which flags map to which transactions.

fix: allow flag maps when submitting NFToken txs

---

packages/xrpl/HISTORY.md
packages/xrpl/src/client/partialPayment.ts
packages/xrpl/src/models/ledger/Ledger.ts
packages/xrpl/src/models/methods/ledgerEntry.ts
packages/xrpl/src/models/methods/tx.ts
packages/xrpl/src/models/transactions/UNLModify.ts
packages/xrpl/src/models/transactions/index.ts
packages/xrpl/src/models/transactions/transaction.ts
packages/xrpl/src/utils/hashes/hashLedger.ts

Currently the explicit responses for `tx` and `ledger` methods do not include psedo-transactions (EnableAmendment, UNLModify, SetFee) even though these transactions should still be found with the above methods. This PR will add these types to the responses.
The response type for `ledger` will allow specifying a custom ledger entry type.

fix: pseudo-transactions for `ledger` and `tx`

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/AMM.ts
packages/xrpl/src/models/ledger/AccountRoot.ts
packages/xrpl/src/models/ledger/Amendments.ts
packages/xrpl/src/models/ledger/BaseLedgerEntry.ts
packages/xrpl/src/models/ledger/Bridge.ts
packages/xrpl/src/models/ledger/Check.ts
packages/xrpl/src/models/ledger/DepositPreauth.ts
packages/xrpl/src/models/ledger/DirectoryNode.ts
packages/xrpl/src/models/ledger/Escrow.ts
packages/xrpl/src/models/ledger/FeeSettings.ts
packages/xrpl/src/models/ledger/Ledger.ts
packages/xrpl/src/models/ledger/LedgerEntry.ts
packages/xrpl/src/models/ledger/LedgerHashes.ts
packages/xrpl/src/models/ledger/NFTokenOffer.ts
packages/xrpl/src/models/ledger/NFTokenPage.ts
packages/xrpl/src/models/ledger/NegativeUNL.ts
packages/xrpl/src/models/ledger/Offer.ts
packages/xrpl/src/models/ledger/PayChannel.ts
packages/xrpl/src/models/ledger/RippleState.ts
packages/xrpl/src/models/ledger/SignerList.ts
packages/xrpl/src/models/ledger/Ticket.ts
packages/xrpl/src/models/ledger/XChainOwnedClaimID.ts
packages/xrpl/src/models/ledger/XChainOwnedCreateAccountClaimID.ts
packages/xrpl/src/models/ledger/index.ts
packages/xrpl/src/models/methods/accountObjects.ts
packages/xrpl/src/models/methods/ledger.ts
packages/xrpl/src/models/methods/ledgerData.ts

- Add missing `type` param
- Clean up typing of `type` param and the response property `account_objects` of the `account_objects` request.
- Create interfaces `HasPreviousTxnID` and `MissingPreviousTxnID`. This helps clean up type checking with regard to the presence of `PreviousTxnID` and `MissingPreviousTxnID`
This field was missing.
https://xrpl.org/ledger_data.html
N/A

fix: add `type` param to `ledger` & `ledger_data`

---

CONTRIBUTING.md
packages/xrpl/HISTORY.md

With xrpl@3.0 coming out we are fully ending support for ripple-lib

docs: End of Life ripple-lib

---

UNIQUE_SETUPS.md
package-lock.json
package.json
packages/isomorphic/HISTORY.md
packages/isomorphic/README.md
packages/isomorphic/package.json
packages/isomorphic/src/ws/browser.ts
packages/isomorphic/src/ws/index.ts
packages/isomorphic/ws/package.json
packages/xrpl/HISTORY.md
packages/xrpl/package.json
packages/xrpl/src/client/connection.ts
packages/xrpl/src/client/index.ts
packages/xrpl/src/models/methods/subscribe.ts
packages/xrpl/test/createMockRippled.ts
packages/xrpl/webpack.base.config.js

Reduces filesize by 3kb minified and gzipped or 2.8% and reduces bundler config steps.
- Move `WSWrapper` to `@xrpl/isomorphic` to remove the need to add mapping of `ws` to `WSWrapper` file in bundler configs
- Switch to `eventemitter3` which is smaller than `events` by almost 1kb and will not require a mapping to node's `events` in `vite` bundling. `webpack` always automatically maps it.
- max listeners is not a thing for `eventemitter3` so we do not need to set it to `Infinity`. `ws` uses the native event emitter which does still need that to be set.
- Remove `eventemitter2` which was only used in tests and was replaced with `eventemitter3`
BREAKING CHANGE: Configuration for frontend bundlers has changed for `ws`

feat: isomorphic sockets and use eventemitter3

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/transactions/NFTokenBurn.ts
packages/xrpl/src/models/transactions/NFTokenCreateOffer.ts
packages/xrpl/src/models/transactions/NFTokenMint.ts
packages/xrpl/src/models/transactions/XChainAccountCreateCommit.ts
packages/xrpl/src/models/transactions/XChainAddAccountCreateAttestation.ts
packages/xrpl/src/models/transactions/XChainAddClaimAttestation.ts
packages/xrpl/src/models/transactions/XChainClaim.ts
packages/xrpl/src/models/transactions/XChainCommit.ts
packages/xrpl/src/models/transactions/XChainCreateClaimID.ts
packages/xrpl/src/models/transactions/accountDelete.ts
packages/xrpl/src/models/transactions/accountSet.ts
packages/xrpl/src/models/transactions/checkCreate.ts
packages/xrpl/src/models/transactions/common.ts
packages/xrpl/src/models/transactions/escrowCancel.ts
packages/xrpl/src/models/transactions/escrowCreate.ts
packages/xrpl/src/models/transactions/escrowFinish.ts
packages/xrpl/src/models/transactions/payment.ts
packages/xrpl/src/models/transactions/paymentChannelCreate.ts
packages/xrpl/test/models/NFTokenCreateOffer.test.ts
packages/xrpl/test/models/accountDelete.test.ts
packages/xrpl/test/models/accountSet.test.ts
packages/xrpl/test/models/checkCreate.test.ts
packages/xrpl/test/models/escrowCancel.test.ts
packages/xrpl/test/models/escrowCreate.test.ts
packages/xrpl/test/models/escrowFinish.test.ts
packages/xrpl/test/models/payment.test.ts
packages/xrpl/test/models/paymentChannelCreate.test.ts

Fields that were encoded as STAccounts were turning `''` into `rrrrrrrrrrrrrrrrrrrrrhoLvTp` the ACCOUNT_ZERO account. They will now throw a `ValidationError`.
Invalid addresses on a transaction now throws a `ValidationError` when submitting a transaction instead of `Error('checksum_invalid')`.
This change updates some error messages for fields a few fields that aren't accounts, `DestinationTag` or `NFTokenID`.  They will still be of type `ValidationError`.
Fixes: #2517 and #2475

fix: tx fields for accounts allowing empty string

---

packages/xrpl/.gitignore
packages/xrpl/README.md
packages/xrpl/package.json

The `xrpl` package had a less than helpful docs when viewed on the npm website. The fix is a workaround that copies the root `README` over to `packages/xrpl/README.md` during the `prepare` lifecycle phase.

fix: copy root README during `xrpl` publish

---

packages/secret-numbers/HISTORY.md
packages/secret-numbers/package.json
packages/secret-numbers/src/index.ts
packages/secret-numbers/src/schema/Account.ts
packages/secret-numbers/src/utils/index.ts
packages/secret-numbers/test/api.test.ts
packages/secret-numbers/test/utils.test.ts

The config was not applied when it was moved to the monorepo

chore(lint): apply prettier to secret-numbers

---

packages/xrpl/HISTORY.md
packages/xrpl/src/client/index.ts
packages/xrpl/src/client/partialPayment.ts
packages/xrpl/src/models/ledger/Ledger.ts
packages/xrpl/src/models/methods/submit.ts
packages/xrpl/src/models/methods/tx.ts
packages/xrpl/src/models/transactions/index.ts
packages/xrpl/src/models/transactions/transaction.ts
packages/xrpl/src/sugar/submit.ts
packages/xrpl/src/utils/hashes/hashLedger.ts
packages/xrpl/test/integration/requests/submit.test.ts
packages/xrpl/test/integration/utils.ts

BREAKING CHANGE: `Transaction` type has been redefined to include all transactions and `SubmittableTransaction` was created to define the old value. The following functions which only handle transactions to be submitted now use `SubmittableTransaction`:
* `Client.autofill`
* `Client.submit`
* `Client.submitAndWait`
* `Client.prepareTransaction`
* `getSignedTx`
* `isAccountDelete`
Closes #2519
This improves the type names to better reflect their usage.

refactor: type `Transaction` to include all tx

---

packages/ripple-binary-codec/src/enums/index.ts
packages/ripple-keypairs/test/api.test.ts
packages/secret-numbers/HISTORY.md
packages/secret-numbers/src/index.ts
packages/secret-numbers/src/schema/Account.ts
packages/secret-numbers/test/api.test.ts
packages/secret-numbers/test/utils.test.ts
packages/xrpl/src/utils/index.ts

BREAKING CHANGE: Moved all methods that were on `Utils` in `@xrplf/secret-numbers` are now individually exported. This affects:
- Utils.randomEntropy,
- Utils.randomSecret
- Utils.entropyToSecret
- Utils.secretToEntropy
- Utils.calculateChecksum
- Utils.checkChecksum
- Utils.parseSecretString

refactor: remove `import *` where able

---

packages/ripple-keypairs/karma.config.js
packages/ripple-keypairs/package.json
packages/ripple-keypairs/test/api.test.ts
packages/ripple-keypairs/test/getAlgorithmFromKey.test.ts
packages/ripple-keypairs/test/webpack.config.js
packages/ripple-keypairs/tsconfig.build.json
packages/ripple-keypairs/tsconfig.json

- Update tests to use jasmine compatible functions. This means removing `toThrowErrorMatchingInlineSnapshot` and manually removing indention to compare some of the complexly formatted error messages.
- Remove usages of `assert` library in keypairs tests.

test: run ripple-keypairs tests in the browser

---

package-lock.json
package.json
packages/ripple-binary-codec/package.json
packages/ripple-binary-codec/test/signing-data-encoding.test.js
packages/xrpl/test/integration/finalTest.test.ts
packages/xrpl/test/integration/fundWallet.test.ts
packages/xrpl/test/integration/integration.test.ts
packages/xrpl/test/shamap.test.ts

Right now we have 5 testing library dependencies. This eliminates `assert`. `jest`, `jasmine`, `chai` and `karma` are the remaining ones.

feat: remove `assert` library as a testing dep

---

packages/xrpl/src/utils/collections.ts
packages/xrpl/test/utils/collections.test.ts

feat: add unit tests for collection utils

---

packages/xrpl/HISTORY.md
packages/xrpl/src/utils/hashes/hashLedger.ts
packages/xrpl/test/utils/hashLedger.test.ts
packages/xrpl/test/utils/hashes.test.ts

I was running the binary codec across a ledger with an `EnableAmendment` transaction and ran into an issue when double checking the transaction hash.
Added a test.

fix: add support for pseudo-transactions to `hashSignedTx`

---

packages/xrpl/HISTORY.md
packages/xrpl/src/utils/parseNFTokenID.ts
packages/xrpl/test/utils/parseNFTokenID.test.ts

Fix taxon calculation for NFTokenID
If NFToken taxon or serial is too big to be handled as number it could be calculated wrong

chore: fix nftoken taxon calculation

---

UNIQUE_SETUPS.md

React native no longer needs a polyfill after `xrpl@3.0.0-beta.1`

docs: remove Buffer polyfill for react-native

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/AMM.ts

Fix `AMM` ledger object's `LPTokenBalance` type to `IssuedCurrencyAmount`. It's incorrectly set to `Currency`

fix AMM ledger object's LPTokenBalance type to IssuedCurrencyAmount

---

MIGRATION.md

3.0 Migration guide that explains the reason for 3.0 as well as the migration steps.  Will be repurposed into a blog post as well.

docs: 3.0 migration guide

---

MIGRATION.md

Couple points of confusion / clarification added from migrating xrpl.org
- Adds a note that `xrpToDrops` is unchanged (which can be easily assumed since the "reverse" is modified)
- Adds a list of polyfills that are removed to be very explicit about how to migrate if you already have polyfills (it's backwards compatible, but this is where the size reduction happens!)
Inspection (these additional steps / explanations point to things I had to figure out when migrating xrpl.org)

Update migration guide

---

package-lock.json

Rebasing with a package-lock.json can be hard and two entries were missed, `ws` and `node-releases`.

fix: package-lock.json after rebase with main

---

packages/xrpl/HISTORY.md
packages/xrpl/src/client/index.ts
packages/xrpl/test/client/requestAll.test.ts
packages/xrpl/test/client/requestNextPage.test.ts
packages/xrpl/test/fixtures/rippled/index.ts
packages/xrpl/test/fixtures/rippled/ledgerDataFirstPageEmpty.json
packages/xrpl/test/utils/hasNextPage.test.ts

The `client.requestAll` method was failing when it had an initial empty list of objects. This sometimes happens when there is an object filter, such as on `account_objects. This PR fixes that issue.
This issue caused problems in some production code.
Added a unit test.

fix: get `client.requestAll` to handle filters better

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/transactions/AMMDeposit.ts

Fix https://github.com/XRPLF/xrpl.js/issues/2666
This PR introduces additional flags used in the AMM-related transactions. I'm using these lines of code as the source of truth: https://github.com/XRPLF/rippled/blob/69143d71f8973e33b701d7becc19da2ad6a68b68/src/ripple/protocol/TxFlags.h#L166
This change brings forth certain AMMFlags into the xrpl-js client library.
Do I need to update HISTORY file? this change implements what was promised in the AMM-transaction documentation.
I'm not familiar with the AMM-transactions to write unit tests for all these flags. Please let me know if you have any ideas.

additional amm flags are introduced

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/RippleState.ts

Add missing `lsfAMMNode` flag  to `RippleState` ledger object
Current tests pass.

fix: add missing lsfAMMNode flag

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/transactions/metadata.ts

Example transaction where a `DeletedNode` has both `PreviousFields` and `FinalFields`: https://livenet.xrpl.org/transactions/424661CF1FD3675D11EC910CF161979553B6D135F9BD03E6F8D4611D88D27581/raw
N/A

fix: add `PreviousFields` to `DeletedNode` metadata type

---

packages/xrpl/src/models/transactions/oracleSet.ts
packages/xrpl/test/models/oracleSet.test.ts

Add input check for `OracleSet` params `AssetPrice` and `Scale` either being both present or excluded.
Added unit tests to verify this validation.

feat: add input check for `OracleSet` params `AssetPrice` and `Scale`

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/methods/index.ts
packages/xrpl/src/models/methods/nftsByIssuer.ts

Title
Following https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/clio-methods/nfts_by_issuer/ & https://ripplelabs.atlassian.net/jira/software/projects/DEFI/boards/760?assignee=712020%3Aff4deb34-7fc1-428e-a2ee-354e1ddba309&selectedIssue=DEFI-127

Add nfts_by_issuer data type

---

packages/xrpl/HISTORY.md
packages/xrpl/src/Wallet/defaultFaucets.ts
packages/xrpl/src/sugar/autofill.ts
packages/xrpl/test/client/autofill.test.ts
packages/xrpl/test/integration/fundWallet.test.ts
packages/xrpl/test/wallet/fundWallet.test.ts

as stated in the title
The reference to asf-flags pertaining to the Hooks amendment have not been removed.
Certain tests pertaining to hooks testnet faucet have been removed.
No need to add additional tests, this PR removes code.

remove references to the hooks testnet faucet in xrpl.js codebase

---

CONTRIBUTING.md

PR updates the test references in `CONTRIBUTING.md`.

docs: update references in `CONTRIBUTING.md`

---

packages/xrpl/src/client/index.ts

Change the type of the Response to`SimulateJsonResponse` or `SimulateBinaryResponse` according to the setting value of the `binary` option.
- [x ] Refactor (non-breaking change that only restructures code)

Make the simulate response more type-strict

---

packages/ripple-binary-codec/HISTORY.md
packages/xrpl/HISTORY.md
packages/xrpl/src/models/transactions/NFTokenModify.ts
packages/xrpl/test/models/NFTokenModify.test.ts

This is related to the PR: https://github.com/XRPLF/xrpl.js/pull/2726

Add more unit test for DynamicNFT

---

.github/workflows/nodejs.yml
packages/xrpl/HISTORY.md
packages/xrpl/src/client/index.ts
packages/xrpl/src/models/methods/index.ts
packages/xrpl/src/models/methods/ledger.ts
packages/xrpl/src/models/methods/simulate.ts
packages/xrpl/src/sugar/submit.ts
packages/xrpl/test/integration/requests/serverInfo.test.ts
packages/xrpl/test/integration/requests/serverState.test.ts
packages/xrpl/test/integration/requests/simulate.test.ts

This PR adds support to xrpl-py for the new `simulate` RPC.
Spec: https://github.com/XRPLF/XRPL-Standards/tree/master/XLS-0069d-simulate
rippled PR: https://github.com/XRPLF/rippled/pull/5069
TODO

feat: add support for the simulate RPC (XLS-69d)

---

.ci-config/rippled.cfg
packages/xrpl/HISTORY.md
packages/xrpl/src/models/ledger/RippleState.ts
packages/xrpl/src/models/transactions/trustSet.ts
packages/xrpl/test/integration/transactions/offerCreate.test.ts
packages/xrpl/test/integration/transactions/trustSet.test.ts
packages/xrpl/test/models/trustSet.test.ts

This PR implements the Deep-Freeze spec: https://github.com/XRPLF/XRPL-Standards/discussions/220%5D
CPP implementation: https://github.com/XRPLF/rippled/pull/5187/files#
Note: Please do not merge this PR until the CPP implementation is merged into the develop branch of rippled.
New integration tests have been added to validate the Deep-Freeze behavior. Unit tests have been modified to incorporate deep-frozen trust lines.
Once the behavior of Checks is better understood with the deep-frozen trust lines, additional integration tests can be added. However, they introduce non-trivial complexity in the code. Furthermore, such tests are already covered by the cpp implementaion.

Deep Freeze XLS-77d

---

package-lock.json
packages/ripple-binary-codec/HISTORY.md
packages/ripple-binary-codec/package.json
packages/xrpl/HISTORY.md
packages/xrpl/package.json

4.2.0 release

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/methods/subscribe.ts

This PR makes a couple of fixes in the `TransactionStream` model:
* Adds the `hash` field (only for APIv2)
* Updates the `close_time_iso` field to only be in APIv2
Fixes #2938
Checked docs

fix: add `hash` field to `TransactionStream`

---

CONTRIBUTING.md
packages/ripple-binary-codec/CONTRIBUTING.md
packages/ripple-binary-codec/src/enums/README.md
packages/ripple-binary-codec/src/enums/xrpl-definitions-base.ts
packages/ripple-binary-codec/src/enums/xrpl-definitions.ts

This PR adds documentation for how to generate the `definitions.json` output via the new script introduced in #2826, and removes mention of the old script.
#2826 didn't update contributing docs to tell contributors to use the new flow.

chore(docs): update `definitions.json` generation docs

---

packages/ripple-binary-codec/HISTORY.md
packages/ripple-binary-codec/src/types/st-object.ts
packages/ripple-binary-codec/test/definitions.test.ts
packages/ripple-binary-codec/test/tx-encode-decode.test.ts

This PR fixes an issue in ripple-binary-codec to throw an error instead of silently throwing away unknown fields and their values when serializing transactions.
It only errors on `CapitalizedFields` and still silently ignores `lowercaseFields`, as the latter are likely from copy-pasting `tx` outputs or something, rather than an actual error (since all rippled fields must be Capitalized).
I came across this issue when working on a separate PR for a new feature, where my tests would fail for unknown reasons. I had to go into the rippled logs and decode the transaction rippled was receiving to figure out what was happening.
Added a test to make sure this works properly, and fixed existing tests that had the previous assumption.

fix(rbc): throw error instead of throwing away unknown fields

---

packages/xrpl/HISTORY.md
packages/xrpl/src/models/common/index.ts
packages/xrpl/test/integration/requests/ammInfo.test.ts
packages/xrpl/test/integration/setup.ts
packages/xrpl/test/integration/transactions/ammCreate.test.ts
packages/xrpl/test/integration/transactions/ammDeposit.test.ts
packages/xrpl/test/integration/transactions/ammWithdraw.test.ts
packages/xrpl/test/integration/utils.ts

This is an equivalent change for JS referencing - https://github.com/XRPLF/xrpl-py/pull/822

fix: add `MPTCurrency` type

---

package-lock.json
packages/ripple-binary-codec/HISTORY.md
packages/ripple-binary-codec/package.json
packages/xrpl/HISTORY.md
packages/xrpl/package.json

4.3.0 release

---

packages/xrpl/src/models/common/index.ts
packages/xrpl/src/models/transactions/vaultDeposit.ts
packages/xrpl/src/models/transactions/vaultWithdraw.ts

Adds missing `MPTAmount` type to `VaultDeposit` & `VaultWithdraw`
No tests needed since it's a TS fix.

fix: add missing `MPTAmount` type to `VaultDeposit` & `VaultWithdraw`

---

packages/xrpl/snippets/src/permissionedDEX.ts
packages/xrpl/src/models/transactions/common.ts
packages/xrpl/src/models/transactions/offerCreate.ts

This PR aims to address any [pending concerns](https://github.com/XRPLF/xrpl.js/pull/3032#discussion_r2219928832) about the PermissionedDEX implementation in the xrpl.js client library.
Tests exist for the code-paths that are exercised in this PR.

introduce hex validation for domainID in Payment, OfferCreate txn
