XRPLF/xrpl.js

- npm-shrinkwrap.json
- package.json
- src/js/ripple/account.js
- src/js/ripple/index.js
- src/js/ripple/pathfind.js
- src/js/ripple/rangeset.js
- src/js/ripple/remote.js
- src/js/ripple/request.js
- src/js/ripple/server.js
- src/js/ripple/transactionmanager.js
- test/rangeset-test.js
- test/request-test.js
- test/server-test.js
* Changes the behavior of `Request.broadcast()` (which may not have been documented at all)
@shekenahglory 
@miguelportilla
> Request broadcast/filter

- src/js/ripple/server.js
https://github.com/ripple/ripple-lib/issues/68
> Throw on tls error

- src/js/ripple/remote.js
- test/remote-test.js
See: https://ripple.com/build/rippled-apis/#ledger-entry
Rippled request
```js
{
"id": 1,
"command": "ledger_entry",
"type": "offer",
"offer": {"account": "rEQWVz1qN4DWw5J17s3DgXQzUuVYDSpK6M", "seq":5 },
"ledger_index": 10850610
}
```
Response
```js
{
"id": 7,
"status": "success",
"type": "response",
"result": {
"index": "F9DCCD26C770952D216085BF97D7E225F6A8B578ABD066AA92D7D06144B535EE",
"ledger_index": 10850610,
"node": {
"Account": "rEQWVz1qN4DWw5J17s3DgXQzUuVYDSpK6M",
"BookDirectory": "CF8D13399C6ED20BA82740CFA78E928DC8D498255249BA6351038D7EA4C68000",
"BookNode": "0000000000000000",
"Flags": 131072,
"LedgerEntryType": "Offer",
"OwnerNode": "0000000000000000",
"PreviousTxnID": "64FAB660F9F5D9E7183E977701930AD09F372129C56E1685B68A914D8A43CA41",
"PreviousTxnLgrSeq": 10850602,
"Sequence": …
```
> [FEATURE] Remote.prototype.requestOffer

- src/js/ripple/amount.js
- test/amount-test.js
Bug due to isFinite('') -> true
> [FIX] Handle invalid input in parse_human

- src/js/ripple/server.js
- src/js/ripple/utils.js
> Revert "Set User-Agent Header with ripple-lib/{version}"

- src/js/ripple/orderbook.js
- test/fixtures/orderbook.js
- test/orderbook-test.js
Keep track of offer quality from rippled and compute quality on new offers. Quality is important because once an offer is placed, its quality never changes. We should NOT be calculating quality on the fly.
> Offer quality

- src/js/ripple/base.js
check for invalid input in decoded data
> [FIX] fix Base:decode

- src/js/ripple/remote.js
See: https://wiki.ripple.com/Ledger_Format#AccountRoot
> [TASK] Add GlobalFreeze and NoFreeze flags

- docs/GUIDES.md
> Fix link in GUIDES.md

- src/js/ripple/keypair.js
- src/js/ripple/remote.js
- src/js/ripple/seed.js
- src/js/ripple/shamap.js
- src/js/ripple/transaction.js
- src/js/ripple/uint.js
- src/js/ripple/uint128.js
- src/js/ripple/uint160.js
- src/js/ripple/uint256.js
- src/js/ripple/utils.js
Was going to have a stab at multi-sign , KeyPair caching and ed25519 sigs in the near future, so `prepping the work area` so to speak.
@wltsmrz 
@clark800 
A few thoughts/questions/observations:
* Is there anyway to narrow the scope from the whole file to a specific block of code when using comment directives to downgrade from error to warning?
* Does `no-multi-space` (or whatever) really buy much?
* `new-cap` is a pain in the arse: I couldn't get the exceptions for `sjcl.bn` working so just surrounded in <enable></enable>
* JSDoc demands some kind of return, for void, use `@return {void}`
> eslint fixes

- scripts/verify_ledger_json.js
- src/js/ripple/serializedobject.js
@shekenahglory 
Try with ledger 7501326
> Fix SerializedObject.append performance issue

- npm-shrinkwrap.json
bignumber 2.0.7
lodash 3.6.0
lru-cache 2.5.2
> Bump dependency versions

- src/js/ripple/amount.js
- test/amount-test.js
turn off group separator in to_text_full
> [FIX] Amount: to_text_full fix

- src/core/autobridgecalculator.js
- src/core/orderbook.js
pass issuers to AutobridgeCalculator so
it can create offers with right issuers
> [FIX] fix AutobridgeCalculator (RT-3445)

- bin/ci.sh
- package.json
> Use parser: babel-eslint which supports facebook flow

- src/core/remote.js
- test/remote-test.js
Pending https://github.com/ripple/rippled/pull/1171
> Handle validations subscription messages

- src/api/ledger/transaction.js
pass transaction object into callback in case of error
> [FIX] fix getTransaction

- src/core/serializedtypes.js
let to const and syntax update
> Ternary operator syntax fix

- npm-shrinkwrap.json
- package.json
- src/core/server.js
Usage:
```javascript
var remote = new Remote({
proxy: 'http://0.0.0.0:3128',
servers: [ 'wss://s1.ripple.com:443' ]
});
```
> Proxy Support

- src/core/remote.js
- test/remote-test.js
Change `SetRegularkey` to `SetRegularKey` and add test...
> Fix transaction construction for SetRegularKey transactions

- src/api/common/validate.js
- src/api/transaction/sign.js
- src/core/seed.js
- test/api-test.js
- test/seed-test.js
but you still cannot sign transaction with regular key by usign
core.Transaction.sign method
> allow to sign transaction in api.sign using regular key

- src/core/transaction.js
https://github.com/ripple/rippled/commit/4dc573f195c943e4d43e4eff4e09bde18cf6178f
https://github.com/ripple/rippled/commit/7c2478480d90c3d843ba4aa24b329ad430913c2c
> Add DeliverMin setter

- package.json
- src/api/common/schema-validator.js
Fixes issue with fs.readFileSync return type
See: https://github.com/facebook/flow/issues/416
https://github.com/facebook/flow/compare/v0.13.1...v0.14.0
> Update Flow to 0.14

- src/core/remote.js
- src/core/transactionmanager.js
I did a systematic search and I believe these are the last missing conversions.
> Fix snake case method calls

- src/api/common/schema-validator.js
- test/api-test.js
because UInt160 considers valid hex values
> in isValidAddress check that address starting with 'r'

- circle.yml
- npm-shrinkwrap.json
- package.json
- src/amount.js
- src/autobridgecalculator.js
- src/baseconverter.js
- src/currency.js
- src/orderbook.js
- src/orderbookutils.js
- src/seed.js
- src/uint128.js
- src/uint160.js
- src/uint256.js
- test/fixtures/orderbook.js
- test/orderbook-autobridge-test.js
- test/orderbook-test.js
Optimize performance of OrderBook
> Optimize performance (for 0.12 master branch)

- test/amount-test-error.js
- test/fixtures/negative-error.json
"Offer total cannot be negative" error appears
> test that shows how

- src/api/common/errors.js
- src/api/ledger/transaction.js
- src/api/ledger/utils.js
- test/api-test.js
NonContiguousLedgerHistoryError:
When requesting a tx, if maxLedgerVersion and minLedgerVersion provided, check
if min and max are within a non-contiguous range in the ledger's history
PendingLedgerVersionError:
If maxLedgerVersion provided, check if ledger is ahead of the server's last
validated ledger
> Add PendingLedgerVersionError

- src/api/common/utils.js
- src/api/ledger/balances.js
- src/api/ledger/orders.js
- src/api/ledger/transaction.js
- src/api/ledger/trustlines.js
- src/api/ledger/utils.js
- src/api/server/server.js
- src/api/transaction/utils.js
- src/core/orderbook.js
- src/core/remote.js
- src/core/rippleerror.js
- src/core/transaction.js
- src/core/transactionmanager.js
- test/api-test.js
- test/transaction-manager-test.js
copy message from Error instance into RippleError
> make Remote.getLedgerSequence asynchronous

- src/core/request.js
- src/core/transactionmanager.js
- test/request-test.js
add default timeout to Request
> remove Request resubmit logic

- src/core/orderbook.js
- test/orderbook-test.js
When the remote is offline and an orderbook is created with XRP as the `gets` currency, the orderbook never gets properly subscribed because requestOffers doesn't allow a request to go to the queue when remote is disconnected.  Its not a problem for non-native currencies because requestTransferRate waits for the remote to connect.
> allow offers request on orderbook subscribe when disconnected

- src/core/remote.js
- src/core/request.js
- src/core/server.js
- test/remote-test.js
- test/request-test.js
Add default timeout to Request.broadcas
Add default timeout to Remote.createPathFind
Handle 'slowDown' error in many places
> fix Request.broadcast logic 

- src/core/transaction.js
- src/core/transactionmanager.js
- test/transaction-test.js
+ Don't check secret in complete() for multisigned transactions
+ Add LastLedgerSequence autofill test
> Fix Transaction.complete() for multisigned transactions

- src/api/ledger/balances.js
- test/api-test.js
- test/fixtures/api/rippled/account-lines.js
obey limit, do not return XRP if currency or issuer specified
> getBalances fixes:

- src/api/common/errors.js
- src/core/remote.js
- src/core/rippleerror.js
- src/core/utils.js
add toString method on RippleError
> fix error in remote.createPathFind

- npm-shrinkwrap.json
- package.json
```
» node
> ripple = require('ripple-lib')
Error: Cannot find module 'babel-core/polyfill'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/Users/alan/Projects/ripple-connect/node_modules/ripple-lib/dist/npm/index.js:23:3)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
```
> Add babel-polyfill

- docs/index.md
- docs/src/boilerplate.md.ejs
- docs/src/introduction.md.ejs
Rewrite of the introductory content to make the docs much more approachable with less context and foreknowledge.
> Doc introduction changes

- docs/samples/cancelall.js
Needed for cleaning up integration test account periodically
> Add sample code to cancel all orders for a specified account

- npm-shrinkwrap.json
- package.json
Also, addresses remote memory disclosure vulnerability
https://nodesecurity.io/advisories/67
> Update ws to 1.0.1

- Gulpfile.js
- npm-shrinkwrap.json
- package.json
- scripts/ci.sh
- src/common/browser-hacks.js
- test/hacks/phantomhacks.js
- test/localrunner.html
- test/localrunnermin.html
- test/saucerunner.html
test minified version in SauceLabs
> fixes for minified version

- docs/index.md
- docs/src/boilerplate.md.ejs
- docs/src/events.md.ejs
- src/api.js
- src/common/connection.js
- test/connection-test.js
- test/setup-api.js
Alson add `connected` and `disconnected` events.
> Reconnection fix

- scripts/sauce-runner.js
- src/common/connection.js
- src/common/errors.js
- test/connection-test.js
- test/fixtures/rippled/index.js
- test/fixtures/rippled/server-info-syncing.json
- test/mock-rippled.js
- test/setup-api-web.js
- test/setup-api.js
- test/utils/net-utils.js
on reconnect do not emit connected event till server_state is full
handle websocket errors in browsers
> [FIX] on reconnect wait for server to be synced

- README.md
- src/offline/ledgerhash.js
RIPD-1348
https://github.com/ripple/rippled/pull/1915
> Check SHAMapV2 ledger close flag

- README.md
- docs/index.md
- docs/src/basictypes.md.ejs
- docs/src/generateAddress.md.ejs
- docs/src/introduction.md.ejs
- docs/src/offline.md.ejs
- docs/src/transactions.md.ejs
replaces #780 (non-forked branch so that hopefully the tests pass)
>  Rebrand 'Ripple Consensus Ledger' to 'XRP Ledger'

- HISTORY.md
- Fix some typos
- Improve consistency of formatting
> Clean up release history

- package.json
https://github.com/ripple/ripple-keypairs/releases/tag/0.10.1
> Update ripple-keypairs to 0.10.1

- src/ledger/orderbook.ts
> Fix: isSameIssue() should check counterparty

- src/broadcast.ts
> Initialize ledgerVersion to undefined

- src/common/serverinfo.ts
> Use BigNumber internally to compute fee

- docs/index.md
- src/common/schemas/input/get-transactions.json
- src/common/schemas/specifications/payment.json
> Improve documentation of getTransactions params

- .travis.yml
This should work once Travis is running and connected to the repo for GitHub CI.
/cc @intelliot
> new travis.yml

- Gulpfile.js
> don't generate definitions for browser build

- docs/index.md
> Fix link to checkCash

- src/common/serverinfo.ts
- test/api-test.js
- test/mock-rippled.js
> Round XRP fee to 6 decimal places

- src/ledger/parse/utils.ts
depends on https://github.com/ripple/ripple-lib-extensions/pull/37
> feat: add payment channel details to tx

- README.md
This should make it easier to [build](https://github.com/ripple/ripple-lib/issues/835#issuecomment-360922057) ripple-lib.
> Update README.md - How to build ripple-lib

- docs/index.md
- docs/src/specifications.md.ejs
- src/common/schemas/specifications/order.json
Specify that both fields can't be set at the same time.
> Improve Order docs. Fix #776

- docs/index.md
- docs/src/prepareEscrowCreation.md.ejs
- src/transaction/escrow-creation.ts
Fix https://github.com/ripple/ripple-lib/issues/933
> Update escrowCreation error message and docs

- docs/index.md
- src/common/schemas/input/api-options.json
> Update server regex to accommodate UDS

- src/ledger/parse/trustline.ts
- test/api-test.js
- test/fixtures/responses/get-transaction-trust-add-memo.json
- test/fixtures/responses/index.js
- test/fixtures/rippled/index.js
- test/fixtures/rippled/tx/trust-set-add-memo.json
- test/mock-rippled.js
Add memos at trustline.ts.
Replaces https://github.com/ripple/ripple-lib/pull/948
> Add memos at trustline.ts (and unit test)

- src/transaction/payment.ts
- test/api-test.js
> Exclude SendMax from XRP to XRP payments

- .travis.yml
- README.md
- package.json
- yarn.lock
> Support node 10

- src/common/constants.ts
Note where the account root flags are documented on the developers site
> Add comments for accountRootFlags

- APPLICATIONS.md
- README.md
Creating a list of projects and applications that use ripple-lib. Others are welcome to add to this list via PR.
> Add list of applications using ripple-lib

- HISTORY.md
- docs/index.md
- src/api.ts
- src/common/connection.ts
- src/common/schemas/objects/tx-json.json
- src/common/schemas/output/outcome.json
- src/common/schemas/output/submit.json
- src/common/validate.ts
- src/ledger/pathfind.ts
- src/ledger/transaction.ts
- src/ledger/utils.ts
- src/transaction/check-cancel.ts
- src/transaction/check-cash.ts
- src/transaction/check-create.ts
- src/transaction/escrow-cancellation.ts
- src/transaction/escrow-creation.ts
- src/transaction/escrow-execution.ts
- src/transaction/order.ts
- src/transaction/ordercancellation.ts
- src/transaction/payment-channel-claim.ts
- src/transaction/payment-channel-create.ts
- src/transaction/payment-channel-fund.ts
- src/transaction/payment.ts
- src/transaction/settings.ts
- src/transaction/trustline.ts
- src/transaction/types.ts
- src/transaction/utils.ts
- test/api-test.js
- test/connection-test.js
- test/mock-rippled.js
Also cleans up some code and fixes some type errors
> prepareTransaction should not overwrite Sequence

- HISTORY.md
- package.json
- yarn.lock
Update ripple-binary-codec to 0.2.1 and ripple-hashes to 0.3.2
> Update ripple-binary-codec to 0.2.1 to support tecKILLED

- src/common/rangeset.ts
- src/common/utils.ts
Before:
```
{
...
"load": {
"jobTypes": {
"0": {"jobType": "untrustedValidation", "perSecond": 10},
"1": {"jobType": "ledgerData", "peakTime": 2, "perSecond": 2},
"2": {"inProgress": 1, "jobType": "clientCommand", "perSecond": 1},
"3": {"jobType": "transaction", "perSecond": 1},
"4": {"jobType": "batch", "perSecond": 1},
"5": {"jobType": "advanceLedger", "peakTime": 4, "perSecond": 1},
"6": {"jobType": "trustedValidation", "perSecond": 1},
"7": {"jobType": "writeObjects", "perSecond": 1},
"8": {"jobType": "trustedProposal", "perSecond": 1},
"9": {"jobType": "peerCommand", "perSecond": 509},
"10": {"jobType": "diskAccess", "perSecond": 1},
"11": {"jobType": "processTransaction", "perSecond": 1},
"12": {"jobType": "SyncReadNode", "perSecond": 88019},
"13": {"jobType": "AsyncReadNode", …
```
> Fix getServerInfo

- src/api.ts
> APIOptions: extend ConnectionOptions

- APPLICATIONS.md
Added xrpscan.com under Data and Visualization section.
> Updated APPLICATIONS.md and added xrpscan

- src/common/connection.ts
- test/api-test.js
- test/connection-test.js
- test/x-address-api-test.js
Tests were broken in some past PRs.  
@intelliot lets get either Travis or Circle set back up for the repo, so that we can get tests running per-PR. Let me know if I can help with that (I don't have settings access).
Fixes:
1. Connection timeout wasn't being cleared properly / in all cases.
2. Tests were testing outdated error messages
> fix broken tests

- package.json
- src/common/hashes/index.ts
- src/common/utils.ts
- src/ledger/parse/account-order.ts
- src/ledger/parse/fields.ts
- src/ledger/parse/utils.ts
- src/ledger/pathfind.ts
- src/transaction/settings.ts
- src/transaction/sign.ts
- src/transaction/trustline.ts
- src/transaction/utils.ts
- test/api-test.ts
- test/x-address-api-test.js
- yarn.lock
fixes #737
This is a part of #1063, tests & TypeScript are both passing
> update bignumber dependency

- package.json
- src/api.ts
- test/mock-rippled.ts
- yarn.lock
This is a part of #1063, tests & TypeScript are both passing
> update ws dependency

- docs/index.md
- docs/src/prepareTransaction.md.ejs
- src/common/schema-validator.ts
- src/common/schemas/objects/transaction-type.json
- src/common/schemas/output/get-transaction.json
- src/common/schemas/specifications/account-delete.json
- src/common/schemas/specifications/deposit-preauth.json
- src/ledger/parse/account-delete.ts
- src/ledger/parse/transaction.ts
- test/api/getTransaction/index.ts
- test/api/prepareTransaction/index.ts
- test/api/sign/index.ts
- test/fixtures/responses/get-transaction-account-delete.json
- test/fixtures/responses/index.js
- test/fixtures/rippled/index.js
- test/fixtures/rippled/tx/account-delete.json
- test/mock-rippled.ts
- test/ripple-api-test.ts
- test/utils.ts
https://xrpl.org/accountdelete.html
> Add support for AccountDelete

- HISTORY.md
- package.json
Add HISTORY and update version in `package.json` for releasing 1.6.0
> Release 1.6.0

- docs/index.md
- docs/src/offline.md.ejs
You can also generate an X-Address without a connection to the ledger.
> Update documentation for functions that can be called offline

- HISTORY.md
- package.json
Update HISTORY and version number
> Release 1.6.1

- HISTORY.md
As discussed, added to Release as well. /cc @intelliot
> Add Update note to HISTORY.md

- package.json
- src/common/constants.ts
- src/ledger/settings.ts
- yarn.lock
Add TypeScript type (`Settings`) for the return value of `parseAccountFlags`
> Add type for parseAccountFlags

- package.json
- src/common/connection.ts
- test/connection-test.ts
Returns the current minimum reserve, in drops of XRP, that is required
for an account.
> Add api.connection.getReserveBase()

- docs/index.md
- docs/src/rippledAPIs.md.ejs
Just updating a link in the docs
> Update Transaction Streams link

- APPLICATIONS.md
xrp1ntel is now known as [xrpintel](https://twitter.com/DevNullProd/status/1274040282657574915) and include newly launched [ZerpTracker](https://zerptracker.com).
> Update APPLICATIONS.md to reflect latest Dev Null Productions products

- HISTORY.md
- package.json
- yarn.lock
Bump ripple-binary-codec to 1.0.1
Update yarn.lock
> Release 1.8.1

- src/common/connection.ts
fixes #1301 
very much a WIP - as I am not sure how this effects streaming.
> clearing of awaiting response promises when response handled

- snippets/src/reliableTransactionSubmission.ts
- src/api.ts
- src/common/types/objects/ledger.ts
- src/index.ts
This should enable the new snippet to build
> Export types

- HISTORY.md
- docs/index.md
- docs/src/staticMethods.md.ejs
- package.json
- src/api.ts
> Expose address codec methods

- package.json
- snippets/src/paths.ts
- yarn.lock
The file referenced by the start script no longer exists. Even when it did exist, it did not work anyway.
Close #1383
> fix: remove start script

- README.md
Add information for deno and react native in Readme.
> Docs: Deno and React

- src/transaction/types.ts
Tested with the local package. My IDE likes the typings now.
<kbd>![Screen Shot 2021-07-13 at 4 30 50 PM](https://user-images.githubusercontent.com/3401412/125538080-2dca4312-72ea-4399-90a9-48f354e418d8.png)</kbd>
> fix: TrustlineTransaction type (#1458)

- snippets/src/reliableTransactionSubmission.ts
> fix #1474: add type argument to Promise

- test/setup-api-web.ts
- test/setup-api.ts
> fix: add void return type to Promises

- .eslintrc.json
- package.json
- yarn.lock
Fix errors found by eslint
Adding GitHub Actions testing
Before:
```
yarn lint
shell: /usr/bin/bash -e {0}
yarn run v1.22.10
$ eslint 'src/**/*.ts' 'test/*-test.{ts,js}'
/home/runner/work/ripple-lib/ripple-lib/src/common/connection.ts
0:0  error  Parsing error: Cannot read property 'map' of undefined
/home/runner/work/ripple-lib/ripple-lib/src/common/rangeset.ts
0:0  error  Parsing error: Cannot read property 'map' of undefined
/home/runner/work/ripple-lib/ripple-lib/src/common/types/commands/ledger_entry.ts
0:0  error  Parsing error: Cannot read property 'map' of undefined
✖ 3 problems (3 errors, 0 warnings)
```
https://github.com/ripple/ripple-lib/pull/1464/checks?check_run_id=3165057807
Solution:
```
➜ yarn upgrade @typescript-eslint/eslint-plugin@latest
➜ yarn upgrade …
```
> fix: lint errors

- .github/workflows/nodejs.yml
- package.json
- yarn.lock
Runs CI w/ GitHub Actions
Runs unit tests, linting, and build scripts with Node v12, v13, v14, and `.nvmrc`
> Adds Github Actions Testing

- docs/index.md
- docs/src/sign.md.ejs
According to the example, send tx failed. 
The result is: 
```
Tentative result code: telINSUF_FEE_P
Tentative result message: Fee insufficient.
```
> Update multisig doc

- src/api.ts
- src/index.ts
- src/offline/generate-address.ts
- src/offline/utils.ts
- All methods that don’t require a network connection are exported at the top-level of the package.
- These instance methods are now marked as deprecated.
- Removed an empty ts file
[jira ticket](https://ripplelabs.atlassian.net/browse/DEVX-81?atlOrigin=eyJpIjoiNjZiMjNlNWM4MWY4NDUzZGFkNzA3ODMxYWIxYmYwMjciLCJwIjoiaiJ9)
CI Passes
> export offline methods to top-level of package

- package.json
- yarn.lock
Updates ripple-binary-codec to v1.1.3
fixes #1312
> chore: update ripple-binary-codec to 1.1.3

- HISTORY.md
- package.json
Regular release (typically we release every ~2 weeks, but we can release more or less often when it makes sense)
> release: 1.9.8

- src/models/methods/index.ts
- src/models/methods/ping.ts
- src/models/methods/random.ts
This PR creates new TypeScript types for all rippled utility methods (https://xrpl.org/utility-methods.html), the request shapes, response shapes, and stream shapes.
xrpl.js v2.0 models
This PR doesn't change any existing code, so tests are fine.
> Implements TypeScript types for utility method requests/responses

- src/models/methods/fee.ts
- src/models/methods/index.ts
- src/models/methods/manifest.ts
- src/models/methods/serverInfo.ts
- src/models/methods/serverState.ts
This PR creates new TypeScript types for all rippled server info methods (https://xrpl.org/server-info-methods.html), and the request shapes and response shapes.
xrpl.js v2.0 models
This PR doesn't change any existing code, so tests are fine.
> Implements TypeScript types for server info method requests/responses

- docs/index.md
- docs/src/generateFaucetWallet.md.ejs
- docs/src/index.md.ejs
- src/wallet/wallet-generation.ts
- test/fixtures/responses/generate-faucet-wallet.json
- test/fixtures/responses/index.js
Adds documentation for `generateFaucetWallet()`
Adds a short section to docs w/ an example of usage + response.
> docs: Add documentation for generateFaucetWallet()

- HISTORY.md
- package.json
Updates for 1.10 release, specifically `HISTORY.md` and `package.json` version.
> chore: update HISTORY.md and package version

- .eslintrc.js
- test/models/accountDelete.ts
- test/models/accountSet.ts
- test/models/baseTransaction.ts
- test/models/checkCancel.ts
- test/models/checkCash.ts
- test/models/checkCreate.ts
- test/models/depositPreauth.ts
- test/models/escrowCancel.ts
- test/models/escrowCreate.ts
- test/models/escrowFinish.ts
- test/models/offerCancel.ts
- test/models/offerCreate.ts
- test/models/payment.ts
- test/models/paymentChannelClaim.ts
- test/models/paymentChannelCreate.ts
- test/models/paymentChannelFund.ts
- test/models/setRegularKey.ts
- test/models/signerListSet.ts
- test/models/ticketCreate.ts
- test/models/trustSet.ts
- test/utils/computeLedgerHash.ts
- test/utils/dropsToXrp.ts
- test/utils/generateAddress.ts
- test/utils/hashes.ts
- test/utils/verifyPaymentChannelClaim.ts
- test/utils/xrpToDrops.ts
Lints the whole folder
CI passes.
> Lints `test/utils`

- .eslintrc.js
- test/models/accountSet.ts
- test/models/checkCancel.ts
- test/models/checkCash.ts
- test/models/checkCreate.ts
- test/models/payment.ts
Adding linting to xrpl.js
CI passes. Linter doesn't have any errors for `test/models`.
> Lints `test/models`

- package-lock.json
- src/client/connection.ts
- src/client/index.ts
- src/common/ecdsa.ts
- src/common/errors.ts
- src/common/fee.ts
- src/common/index.ts
- src/models/methods/serverInfo.ts
- src/transaction/sign.ts
- test/client/errors.ts
- test/client/getFee.ts
- test/client/getPaths.ts
- test/connection.ts
- test/integration/integration.ts
Title says it all. I didn't lint `src/types` because that's going to be deleted soon.
Linting the whole codebase
CI passes. Linter doesn't have any errors in `src/common/*.ts`.
> Lints `src/common`

- src/wallet/signer.ts
- test/wallet/signer.ts
Responding to final comments in #1573 
Accidentally reverted these fixes before merging. 
CI Passes
> Signer fixes

- APPLICATIONS.md
- README.md
- SECURITY.md
- package-lock.json
- package.json
- snippets/src/reliableTransactionSubmission.ts
- test/localIntegrationRunner.html
- webpack.config.js
Renames `ripple-lib` to `xrpl.js` where neccesary.
Renames `ripple-lib` to `xrpl` in package.json. 
Renames webpacked `ripple-latest.js` to `xrpl-latest.js`
Renames `ripple-lib` to `xrpl.js` in the documentation (README, APPLICATIONS)
> build: rename ripple-lib to xrpl.js

- package.json
publishing the beta
CI passes.
> build: update version for beta

- package-lock.json
- package.json
> build: update ws

- .eslintrc.js
- src/wallet/generateFaucetWallet.ts
- src/wallet/index.ts
- test/wallet/generateFaucetWallet.ts
- test/wallet/index.ts
Linting the whole repo
CI passes.
> Lints `src/wallet` and `test/wallet`

- test/integration/requests/utility.ts
- test/integration/setup.ts
- test/integration/utils.ts
This PR will open when #1596 is done.
> test: adds integration tests for rippled utility methods

- .eslintrc.js
- test/client/combine.ts
- test/client/constructor.ts
- test/client/getBalances.ts
- test/client/getOrderbook.ts
- test/client/hasNextPage.ts
- test/client/isConnected.ts
- test/client/request.ts
- test/client/requestNextPage.ts
- test/client/sign.ts
Modify codebase to abide by the ESLint rules.
Lint Client test files.
Code works fine when tested against CI test cases.
> Refactor: Lint test/client

- package.json
- test/integration/integration.ts
- test/integration/requests/utility.ts
- test/integration/setup.ts
- test/integration/transactions/signerListSet.ts
- test/integration/utils.ts
- test/integration/wallet.ts
Title says it all. Also refactored some helper functions to make it easier to work with them for future tickets.
Integration tests for 2.0
CI passes.
> test: SignerListSet transaction integration tests

- test/integration/integration.ts
- test/integration/transactions/payment.ts
- test/integration/transactions/signerListSet.ts
- test/integration/utils.ts
Integration tests for xrpl.js
CI passes.
> test: integration tests for Payment

- webpack.config.js
> rename browser library

- src/sugar/balances.ts
- src/sugar/orderbook.ts
- test/client/getBalances.ts
- test/client/getOrderbook.ts
- test/fixtures/requests/getOrderbook.json
- test/fixtures/requests/getOrderbookWithXrp.json
- test/fixtures/responses/getOrderbookWithXrp.json
- test/mockRippled.ts
Write Tests for Sugar Functions
Tests according to the new structure of the sugar functions.
Passes all CI tests.
> test: write tests for sugar functions

- .eslintrc.js
- package-lock.json
- package.json
- src/client/connection.ts
- src/client/index.ts
- test/connection.ts
Adjusts `.eslintrc.js` for `@xrplf/eslint-config` v1.4. From my linting convo w/ Greg.
> build: adjust for updates to @xrplf/eslint-config

- test/integration/transactions/depositPreauth.ts
Integration tests for xrpl.js
CI passes.
> test: integration tests for DepositPreauth

- package-lock.json
- package.json
Package wasn't being used anymore
CI passes.
> chore: remove ripple-lib-transactionparser

- src/errors.ts
@mDuo13 was having an issue with browser code, where it would fail because of the error `Uncaught TypeError: Error.captureStackTrace is not a function`. This PR should fix that.
CI passes. @mDuo13 will check if this fixes the problem.
> fix: resolve browser issue with Error.captureStackTrace

- test/integration/index.ts
- test/integration/transactions/trustSet.ts
Adding a test for this transaction: https://xrpl.org/trustset.html#trustset
CI passes
> test: Add TrustSet integration tests

- src/wallet/generateFaucetWallet.ts
Bug reported by @mDuo13 
CI passes.
Integration test for generateFaucetWallet
> fix: make `generateFaucetWallet` functional

- package-lock.json
- package.json
Published beta.2 off of this branch last night, now merging it into the repo.
CI passes.
> build: update beta version to beta.2

- test/integration/transactions/accountDelete.ts
- test/integration/transactions/accountSet.ts
- test/integration/utils.ts
Add Integration tests for Account Transactions
Passes all the tests
> test: Integration tests for Account Transactions

- test/integration/transactions/escrowCancel.ts
- test/integration/transactions/escrowCreate.ts
- test/integration/transactions/escrowFinish.ts
- test/integration/utils.ts
Add Integration tests for Escrow Transactions
Passes all the tests
> test: Add Integration tests for Escrow Transactions

- HISTORY.md
- package-lock.json
- package.json
* Updates the package.json and history.md for version 2.0.1
> Build: Prepare for 2.0.1

- README.md
A user tried the demo code, but it didn't work. This should fix it.
Ran it locally to make sure the demo code worked now
> Update readme with websocket url

- packages/ripple-address-codec/HISTORY.md
- packages/ripple-binary-codec/HISTORY.md
- packages/ripple-keypairs/HISTORY.md
- packages/xrpl/HISTORY.md
Updating the HISTORY.md files for each of the packages.
In preparation for a patch release.
Added a change log for commits in the patch.
None
> Update history for all codecs and xrpl.js

- packages/ripple-address-codec/package.json
- packages/ripple-binary-codec/package.json
- packages/ripple-keypairs/package.json
- packages/xrpl/package.json
Releasing a patch version for all repos.
See HISTORY.md
> Lerna patch

- packages/ripple-binary-codec/HISTORY.md
> chore: update HISTORY for rbc release

- package-lock.json
- packages/ripple-address-codec/package.json
- packages/ripple-binary-codec/package.json
- packages/ripple-keypairs/package.json
- packages/xrpl/package.json
Title says it all. Bumps all patch versions.
> release: release new versions

- package-lock.json
- packages/ripple-binary-codec/HISTORY.md
- packages/ripple-binary-codec/src/enums/definitions.json
- packages/ripple-binary-codec/src/enums/index.ts
- packages/ripple-binary-codec/src/index.ts
- packages/ripple-binary-codec/test/fixtures/nf-token.json
- packages/xrpl/HISTORY.md
- packages/xrpl/src/models/common/index.ts
- packages/xrpl/src/models/methods/accountNFTs.ts
- packages/xrpl/src/models/methods/index.ts
- packages/xrpl/src/models/methods/nftBuyOffers.ts
- packages/xrpl/src/models/methods/nftSellOffers.ts
- packages/xrpl/src/models/transactions/NFTokenAcceptOffer.ts
- packages/xrpl/src/models/transactions/NFTokenBurn.ts
- packages/xrpl/src/models/transactions/NFTokenCancelOffer.ts
- packages/xrpl/src/models/transactions/NFTokenCreateOffer.ts
- packages/xrpl/src/models/transactions/NFTokenMint.ts
- packages/xrpl/src/models/transactions/accountSet.ts
- packages/xrpl/src/models/transactions/common.ts
- packages/xrpl/src/models/transactions/index.ts
- packages/xrpl/src/models/transactions/transaction.ts
- packages/xrpl/test/models/NFTokenAcceptOffer.ts
- packages/xrpl/test/models/NFTokenBurn.ts
- packages/xrpl/test/models/NFTokenCancelOffer.ts
- packages/xrpl/test/models/NFTokenCreateOffer.ts
- packages/xrpl/test/models/NFTokenMint.ts
> feat: NFT support

- CONTRIBUTING.md
When using lerna with a protected branch, there's different steps required to publish.
These were the steps used in the latest release of xrpl packages.
* Updated release steps with the work around we have to use for a protected branch based on this thread: https://github.com/lerna/lerna/issues/1957#issuecomment-476894990
N/A
> Updating CONTRIBUTING with the correct steps

- package-lock.json
- packages/ripple-address-codec/package.json
- packages/ripple-binary-codec/package.json
- packages/ripple-keypairs/package.json
- packages/xrpl/package.json
> Update versions for release

- CONTRIBUTING.md
This PR fixes how lerna operates, so it does what we actually want it to do.
We no longer have to publish every single package when they haven't changed.
> chore: fix lerna publishing steps

- packages/ripple-address-codec/.eslintrc.js
- packages/ripple-address-codec/src/index.ts
- packages/ripple-address-codec/src/utils.ts
- packages/ripple-address-codec/src/xrp-codec.ts
> address codec linting

- package-lock.json
- packages/ripple-binary-codec/package.json
Update package.json for release
> Release ripple-binary-codec version 1.3.2

- package-lock.json
- packages/ripple-binary-codec/package.json
- packages/xrpl/package.json
Latest release of XRPL.js packages.
See HISTORY.md
CI passes
> 2.2.0 xrpl.js release

- packages/xrpl/src/models/common/index.ts
One return field from nft_buy_offers and nft_sell_offers changed, which was missed in the renaming
Missed field in renaming
> fix return field of nft offer

- package-lock.json
- packages/xrpl/package.json
> release(xrpl): 2.2.3

- CONTRIBUTING.md
Revised the steps to involve fewer PRs. Should save some time during xrpl.js releases going forward.
> Remove extraneous PR for docs

- package-lock.json
- package.json
- packages/xrpl/HISTORY.md
- packages/xrpl/package-lock.json
Some of our dependencies had security warnings, so I ran `npm audit --force` to fix those issues.
npm was giving warnings when building.
CI passes and build completes successfully.
> Run npm audit fix --force

- package-lock.json
- package.json
- packages/xrpl/package.json
- packages/xrpl/webpack.config.js
Improve debugging for users loading in library via unpkg or jsdelivr
> feat(source-maps): Generate source-maps for browser build

- APPLICATIONS.md
> fix: link to XRPL Rosetta (ThreeXRP.dev)

- package-lock.json
- packages/ripple-binary-codec/HISTORY.md
- packages/ripple-binary-codec/package.json
- packages/xrpl/HISTORY.md
- packages/xrpl/package-lock.json
- packages/xrpl/package.json
Updates HISTORY.md files and does lerna version for `xrpl` and `ripple-binary-codec`.
> Release xrpl packages

- README.md
Invite users to create Github issues whenever they encounter a problem with the library or have a question.
Part of [DGE-457](https://ripplelabs.atlassian.net/browse/DGE-457).
> Update README with invitation to report an issue

- packages/xrpl/HISTORY.md
Update the HISTORY.md file with the newest package version on the 2.4.0 release.
Forgot to include this when releasing.
> Update HISTORY.md with last version

- packages/xrpl/HISTORY.md
- packages/xrpl/src/models/methods/subscribe.ts
Add and document more fields on the ValidationStream interface
Fixes #2095
> fix(ValidationStream): Add `cookie` and `data` to interface

- .vscode/settings.json
- packages/xrpl/src/models/ledger/AccountRoot.ts
- packages/xrpl/src/models/transactions/metadata.ts
- packages/xrpl/src/models/transactions/signerListSet.ts
- packages/xrpl/test/models/signerListSet.ts
This PR fixes a few typos found in the repo (mostly in the documentation).
I just downloaded a new VSCode extension that checks for typos.
N/A
* Go through the entire repo looking for spelling errors (it might be a bug)
> fix: fix typos

- package-lock.json
- packages/xrpl/HISTORY.md
- packages/xrpl/package-lock.json
- packages/xrpl/package.json
> 2.5.0 release

- packages/xrpl/snippets/src/multisigning.ts
Add quality of life code snippets for multisigning.
> docs: code snippets for multisigning

- packages/xrpl/HISTORY.md
- packages/xrpl/src/Wallet/fundWallet.ts
- packages/xrpl/test/integration/fundWallet.ts
related to DGE [649](https://ripplelabs.atlassian.net/jira/software/projects/DGE/boards/524?selectedIssue=DGE-649)
Add amount field to allow custom amount to be passed in for faucet transactions. 
- [X ] New feature (non-breaking change which adds functionality)
changed integration test, unit tests and integration tests passed.
> add amount field to faucet

- .github/workflows/nodejs.yml
This PR adds a timeout if the test runs for longer than 10 minutes.
There have been a lot of hanging tests lately for some reason that don't die for hours.
CI works.
> ci: add timeouts

- .github/workflows/nodejs.yml
This PR adds caching of node_modules to testing. This shaves about a minute from the time to run CI.
Everyone likes speedy CI
Works in CI.
> ci: cache dependencies

- README.md
> Add code sample link to README

- packages/xrpl/snippets/README.md
> Add README.md in snippets folder to point to xrpl.org code samples

- CONTRIBUTING.md
@khancode and I ran into some minor issues/differences that weren't documented.
The CONTRIBUTING release instructions now include details for beta releases.
N/A
> docs: update release instructions with beta details

- packages/xrpl/test/utils/getNFTokenID.test.ts
`parseNFTokenID` -> `getNFTokenID`
> Fix typo in getNFTokenID test name

- CONTRIBUTING.md
Updating to use auto-numbering.
> Update CONTRIBUTING checklist with numbering

- APPLICATIONS.md
Add GemWallet to the list of extensions within the `APPLICATIONS.md` file.
No tests required.
> Update the applications.md file

- README.md
- UNIQUE_SETUPS.md
Add cdn steps and mention how to get sourcemaps.
> docs: detail how to reference on a cdn

- package-lock.json
- package.json
> build(deps-dev): bump webpack from 5.76.0 to 5.81.0

- packages/xrpl/src/Wallet/defaultFaucets.ts
- packages/xrpl/src/Wallet/fundWallet.ts
- packages/xrpl/test/integration/fundWallet.test.ts
- packages/xrpl/test/wallet/fundWallet.test.ts
> fix: move to hooks v3 testnet

- package-lock.json
- package.json
`puppeteer` was removed in #2170 and dependabot won't stop being annoying about it.
Closes #2234
> chore(dev-deps): remove `puppeteer`

- packages/xrpl/HISTORY.md
- packages/xrpl/src/Wallet/defaultFaucets.ts
- packages/xrpl/test/integration/fundWallet.test.ts
Makes it easier for people to use the sidechain devnet.
CI passes.
> feat: add support for sidechain devnet faucet

- package-lock.json
- package.json
- packages/xrpl/package.json
@JST5000 and I had issues publishing with lerna v6 - these issues should be further debugged separately.
Publishing worked after downgrading.
> fix: downgrade lerna

- packages/xrpl/src/models/transactions/common.ts
Slight improvements to transaction common fields descriptions based on "Send a payment" workshop
The descriptions were originally copied from [Transaction Common Fields](https://xrpl.org/transaction-common-fields.html) but we could improve them, especially in the context of the xrpl.js docs
I'm not sure how to re-gen the `docs/` folder to show these changes
> Update tx common field descritpions

- .github/workflows/nodejs.yml
- packages/xrpl/snippets/src/getTransaction.ts
- packages/xrpl/snippets/src/multisigning.ts
- packages/xrpl/src/Wallet/signer.ts
There was an error in the snippets that wasn't caught.
CI passes.
> test: run snippets in CI

- packages/xrpl/src/models/common/index.ts
- packages/xrpl/src/sugar/balances.ts
- packages/xrpl/src/sugar/index.ts
- packages/xrpl/src/utils/getBalanceChanges.ts
> feat: export `Balance` type

- package-lock.json
- package.json
- packages/ripple-address-codec/src/index.ts
- packages/ripple-address-codec/tsconfig.json
- packages/ripple-binary-codec/tsconfig.json
- packages/xrpl/package.json
- packages/xrpl/test/createMockRippled.ts
- packages/xrpl/tsconfig.json
Major version bump of typescript
> feat: bump typescript to 5.x

- .github/workflows/nodejs.yml
- CONTRIBUTING.md
- packages/xrpl/test/integration/README.md
- packages/xrpl/test/integration/requests/serverInfo.test.ts
- packages/xrpl/test/integration/requests/serverState.test.ts
`ports` is added into the response of `server_state` and `server_info` in v1.12 (see https://github.com/XRPLF/rippled/pull/4427)
Ignored this key in the unit test.
> Update docker to xrpllabsofficial/xrpld:1.12.0-b1

- package-lock.json
- packages/ripple-binary-codec/package.json
- packages/xrpl/package.json
Title says it all (I should've included these as part of the previous PR, but accidentally split into two steps)
> release: Update package.json files

- .github/pull_request_template.md
The #1 thing we forget to do when making PRs is update the README
This should make it easier to remember (and more likely for external contributors to know about this requirement).
N/A
> docs: Add README check

- CONTRIBUTING.md
Discord is a good spot to get the word out about new releases, so should be part of our release process.
> docs: Add step to message Discord to release steps

- packages/xrpl/snippets/src/bridgeTransfer.ts
- packages/xrpl/src/Wallet/defaultFaucets.ts
This PR switches from a decommissioned bridge to a new bridge in the snippet.
The testing bridge was moved from sidechain-net1 to Devnet.
CI passes now.
> chore: fix sidechain networks

- packages/xrpl/snippets/src/bridgeTransfer.ts
The Devnet bridge was updated again.
Snippet works and passes in CI.
> fix: update door account for bridge snippet

- packages/xrpl/HISTORY.md
- packages/xrpl/src/Wallet/defaultFaucets.ts
- packages/xrpl/src/Wallet/fundWallet.ts
- packages/xrpl/test/integration/fundWallet.test.ts
The AMM dev network will be decommissioned on the 12/8
> feat: remove AMM devnet

- packages/ripple-binary-codec/CONTRIBUTING.md
- packages/ripple-binary-codec/src/README.md
It's not obvious how to add a new type to the library, run tests, and how to write tests. This documents that process better.
This should help any potential contributors understand the binary-codec library faster.
N/A
> Add a CONTRIBUTING.md to `ripple-binary-codec`

- MIGRATION.md
> Fix: Migration guide package version formatting

- packages/xrpl/HISTORY.md
- packages/xrpl/src/models/transactions/payment.ts
- packages/xrpl/test/models/utils.test.ts
The codebase contains an incorrect flag name `tfNoDirectRipple`. This is modified to adhere to the documentation as `tfNoRippleDirect`
- [] Refactor (non-breaking change that only restructures code)
- [] No, this change does not impact library users
The existing unit tests have been updated to use the correct flag name
> rectify the flag name tfNoRippleDirect

- package-lock.json
- packages/isomorphic/HISTORY.md
- packages/isomorphic/package.json
- packages/ripple-binary-codec/HISTORY.md
- packages/ripple-binary-codec/package.json
- packages/xrpl/HISTORY.md
- packages/xrpl/package.json
> release 3.1.0

- .coderabbit.yaml
> chore: remove code rabbit sequence diagram

- packages/xrpl/src/models/transactions/MPTokenIssuanceCreate.ts
- packages/xrpl/src/models/transactions/MPTokenIssuanceSet.ts
- packages/xrpl/test/models/MPTokenIssuanceCreate.test.ts
- packages/xrpl/test/models/MPTokenIssuanceSet.test.ts
> add more mpt flag validations

- package-lock.json
- packages/xrpl/HISTORY.md
Update packages to resolve potential security issues.
Packages:
- cross-spawn
- micromatch
- tar
- ws
- @types/ws
- body-parser
- braces
Existing tests should pass.
> fix: update packages to resolve potential security issues

- packages/xrpl/package.json
versions compromised
- 4.2.1
- 4.2.2
- 4.2.3
- 4.2.4
- 2.14.2
> bump to publish non compromised version

- packages/xrpl/HISTORY.md
- packages/xrpl/src/models/transactions/delegateSet.ts
- packages/xrpl/test/models/delegateSet.test.ts
Feature enhancement for https://github.com/XRPLF/xrpl.js/issues/2989
Adds unit test
> fix: add pseudo transactions to NON_DELEGATABLE_TRANSACTIONS

- package-lock.json
- packages/ripple-address-codec/package.json
- packages/ripple-binary-codec/HISTORY.md
- packages/ripple-binary-codec/package.json
- packages/ripple-keypairs/package.json
- packages/secret-numbers/package.json
- packages/xrpl/package.json
ripple-binary-codec 2.4.1 patch release
> ripple-binary-codec 2.4.1 patch release
